---
title: 'EldersAIR: ambient temp data'
author: "Ethan Walker"
date: "Started 26 May 2021, Updated 26 May 2021"
output:
  powerpoint_presentation: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, eval = TRUE, 
                      include = TRUE, warning = FALSE,
                      fig.height = 6, fig.width = 8)
```

```{r, message=FALSE}
library(tidyverse)
library(readxl)
library(naniar)
library(lubridate)
library(zoo)
library(knitr)
jv_palette <- c("#330099","#CC0066","#FF6633", 
                 "#0099CC", "#FF9900","#CC6633",
                  "#FF3366", "#33CC99", "#33999")
cbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", 
               "#0072B2", "#D55E00", "#CC79A7")
```


```{r}
# Load data

file_path <- c("C:/Users/ethan.walker/Box/Ethan Walker UM/R/EldersAIR/")

# Ambient weather data pulled from: https://www.ncdc.noaa.gov/cdo-web/search 

# NN weather data from Window Rock
nn_weather_data <- read_csv(paste0(file_path, "Input/ambient/nn_weather.csv")) %>% 
  mutate(area = "NN",
         sampling_date = mdy(DATE),
         temp_amb_ave = as.numeric(TAVG),
         temp_amb_max = as.numeric(TMAX),
         temp_amb_min = as.numeric(TMIN)) %>% 
  select(area:temp_amb_min)

# NPT weather data from Lewiston
npt_weather_data <- read_csv(paste0(file_path, "Input/ambient/npt_weather.csv")) %>% 
  mutate(area = "NPT",
         sampling_date = mdy(DATE),
         temp_amb_ave = as.numeric(TAVG),
         temp_amb_max = as.numeric(TMAX),
         temp_amb_min = as.numeric(TMIN)) %>% 
  select(area:temp_amb_min)

elders_weather_data <- rbind(nn_weather_data, npt_weather_data) %>% 
  arrange(area, sampling_date)

elders_cleaned_dataset_by_visit <- read_rds(paste0(file_path, "Output/elders_cleaned_dataset_by_visit.rds")) %>% 
  left_join(elders_weather_data, by = c("area", "sampling_date"))
```


```{r}
temp_summary <- elders_cleaned_dataset_by_visit %>% 
  group_by(area, winter_id) %>% 
  summarize(mean(temp_amb_ave, na.rm = T),
            mean(temp_amb_max, na.rm = T),
            mean(temp_amb_min, na.rm = T),
            median(temp_amb_ave, na.rm = T),
            median(temp_amb_max, na.rm = T),
            median(temp_amb_min, na.rm = T))
temp_summary
```

