---
title: "Elders health and elder files data cleaning"
author: "Ethan Walker"
date: "Started 28 Feb 2020, Updated 10 March 2021"
output: pdf_document 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, eval = TRUE, 
                      include = TRUE, warning = FALSE)
```

```{r, message=FALSE}
library(tidyverse)
library(readxl)
library(naniar)
library(lubridate)
library(zoo)
library(knitr)
jv_palette <- c("#330099","#CC0066","#FF6633", 
                 "#0099CC", "#FF9900","#CC6633",
                  "#FF3366", "#33CC99", "#33999")
```

```{r}
file_path <- c("C:/Users/ethan.walker/Box/Ethan Walker UM/R/EldersAIR/")

# Load data
elders_ids_linked <- read_rds(paste0(file_path, "Output/elders_ids_linked.rds"))
```


################# At Home Log ###############

# Load and merge files from different locations
```{r}
nn_athomelog_initial <- read_xlsx(paste0(file_path, "Input/NN/athomelog.xlsx"),
                                   na = "NULL") %>% 
  mutate(home_winter_id = as.character(HomeWinterID),
         adult_id_num = as.character(AdultID),
         area = "NN",
         sampling_visit = as.numeric(SamplingVisit),
         at_home_day = as.factor(Day),
         "at_home_00:00:00" = as.factor("Yes"),
         "at_home_01:00:00" = as.factor("Yes"),
         "at_home_02:00:00" = as.factor("Yes"),
         "at_home_03:00:00" = as.factor("Yes"),
         "at_home_04:00:00" = as.factor("Yes"),
         "at_home_05:00:00" = as.factor("Yes"),
         "at_home_06:00:00" = as.factor("Yes"),
         "at_home_07:00:00" = as.factor(AtHome1),
         "at_home_08:00:00" = as.factor(AtHome2),
         "at_home_09:00:00" = as.factor(AtHome3),
         "at_home_10:00:00" = as.factor(AtHome4),
         "at_home_11:00:00" = as.factor(AtHome5),
         "at_home_12:00:00" = as.factor(AtHome6),
         "at_home_13:00:00" = as.factor(AtHome7),
         "at_home_14:00:00" = as.factor(AtHome8),
         "at_home_15:00:00" = as.factor(AtHome9),
         "at_home_16:00:00" = as.factor(AtHome10),
         "at_home_17:00:00" = as.factor(AtHome11),
         "at_home_18:00:00" = as.factor(AtHome12),
         "at_home_19:00:00" = as.factor(AtHome13),
         "at_home_20:00:00" = as.factor(AtHome14),
         "at_home_21:00:00" = as.factor(AtHome15),
         "at_home_22:00:00" = as.factor(AtHome16),
         "at_home_23:00:00" = as.factor("Yes")) %>% 
  select(home_winter_id:"at_home_23:00:00")



npt_athomelog_initial <- read_xlsx(paste0(file_path, "Input/NP/athomelog.xlsx"),
                                   na = "NULL") %>% 
  mutate(home_winter_id = as.character(HomeWinterID),
         adult_id_num = as.character(AdultID),
         area = "NPT",
         sampling_visit = as.numeric(SamplingVisit),
         at_home_day = as.factor(Day),
         "at_home_00:00:00" = as.factor("Yes"),
         "at_home_01:00:00" = as.factor("Yes"),
         "at_home_02:00:00" = as.factor("Yes"),
         "at_home_03:00:00" = as.factor("Yes"),
         "at_home_04:00:00" = as.factor("Yes"),
         "at_home_05:00:00" = as.factor("Yes"),
         "at_home_06:00:00" = as.factor("Yes"),
         "at_home_07:00:00" = as.factor(AtHome1),
         "at_home_08:00:00" = as.factor(AtHome2),
         "at_home_09:00:00" = as.factor(AtHome3),
         "at_home_10:00:00" = as.factor(AtHome4),
         "at_home_11:00:00" = as.factor(AtHome5),
         "at_home_12:00:00" = as.factor(AtHome6),
         "at_home_13:00:00" = as.factor(AtHome7),
         "at_home_14:00:00" = as.factor(AtHome8),
         "at_home_15:00:00" = as.factor(AtHome9),
         "at_home_16:00:00" = as.factor(AtHome10),
         "at_home_17:00:00" = as.factor(AtHome11),
         "at_home_18:00:00" = as.factor(AtHome12),
         "at_home_19:00:00" = as.factor(AtHome13),
         "at_home_20:00:00" = as.factor(AtHome14),
         "at_home_21:00:00" = as.factor(AtHome15),
         "at_home_22:00:00" = as.factor(AtHome16),
         "at_home_23:00:00" = as.factor("Yes")) %>% 
  select(home_winter_id:"at_home_23:00:00")     


# Combine logs from all areas
elders_at_home_log <- rbind(nn_athomelog_initial, npt_athomelog_initial) %>% 
  right_join(elders_ids_linked, c("area", "home_winter_id", "adult_id_num")) %>% 
  arrange(area, adult_id_num, winter_id, sampling_visit, at_home_day) %>% 
  group_by(area, adult_id_num, winter_id, sampling_visit, at_home_day) %>% 
  pivot_longer(cols = c("at_home_00:00:00":"at_home_23:00:00"), names_to = "sample_time",
                        values_to = "at_home") %>% 
  ungroup() %>% 
  separate(sample_time, c("trash", "sample_time"), sep = "at_home_", remove = FALSE) %>% 
  select(-trash) %>% 
  mutate(sample_time = as.character(sample_time)) %>% 
  mutate_at(vars(home_winter_id:home), as.factor)

summary(elders_at_home_log)


# write_rds(elders_at_home_log, paste0(file_path, "Output/elders_at_home_log_clean.rds"))

save_var_names <- data.frame(t(elders_at_home_log)) %>% 
  rownames_to_column() %>% 
  select(rowname)

# write_csv(save_var_names, paste0(file_path, "Output/at_home_var_names.csv"))
```



################# Health History ###############

# Load and merge files from different locations
```{r}
nn_healthhistory_initial <- read_xlsx(paste0(file_path, "Input/NN/healthhistory.xlsx"),
                                      na = "NULL") %>% 
  rename_all(~str_replace_all(., "Date", "_date")) %>% 
  rename_all(tolower) %>% 
  mutate(home_winter_id = as.character(homewinterid),
         adult_id_num = as.character(adultid),
         area = "NN",
         rheum_arth = ra,
         rheum_arth_date = ra_date) %>% 
  select(-id:-homewinterid, -ra, -ra_date, -whatmissing:-ignorereason) %>% 
  select(adult_id_num, area, rheum_arth, rheum_arth_date,
         lupus:cigarspipes)
         


npt_healthhistory_initial <- read_xlsx(paste0(file_path, "Input/NP/healthhistory.xlsx"),
                                      na = "NULL") %>% 
  rename_all(~str_replace_all(., "Date", "_date")) %>% 
  rename_all(tolower) %>% 
  mutate(home_winter_id = as.character(homewinterid),
         adult_id_num = as.character(adultid),
         area = "NPT",
         rheum_arth = ra,
         rheum_arth_date = ra_date) %>% 
  select(-id:-homewinterid, -ra, -ra_date, -whatmissing:-ignoremissingdata) %>% 
  select(adult_id_num, area, rheum_arth, rheum_arth_date,
         lupus:cigarspipes)  


# Combine logs from all areas
elders_health_hx <- rbind(nn_healthhistory_initial, npt_healthhistory_initial) %>% 
  right_join(elders_ids_linked, c("area", "adult_id_num")) %>% 
  select(area, adult_id_num, adult_id_char:treatment, rheum_arth:cigarspipes) %>% 
  arrange(area, adult_id_num, winter_id) %>% 
  mutate_at(vars(area:home), as.factor)

summary(elders_health_hx)

# write_rds(elders_health_hx, paste0(file_path, "Output/elders_health_hx_clean.rds"))


save_var_names <- data.frame(t(elders_health_hx)) %>% 
  rownames_to_column() %>% 
  select(rowname)

#write_csv(save_var_names, paste0(file_path, "Output/health_hx_var_names.csv"))
```



################# Health Extra ###############

# Load and merge files from different locations
```{r}
nn_healthextra_initial <- read_xlsx(paste0(file_path, "Input/NN/healthextra.xlsx"),
                                      na = "NULL") %>% 
  rename_all(tolower) %>% 
  mutate(home_winter_id = as.character(homewinterid),
         adult_id_num = as.character(adultid),
         area = "NN",
         sampling_visit = samplingvisit) %>% 
  select( home_winter_id, adult_id_num, sampling_visit, area, cold2m:bronch2mdr) 
         


npt_healthextra_initial <- read_xlsx(paste0(file_path, "Input/NP/healthextra.xlsx"),
                                      na = "NULL") %>% 
  rename_all(tolower) %>% 
  mutate(home_winter_id = as.character(homewinterid),
         adult_id_num = as.character(adultid),
         area = "NPT",
         sampling_visit = samplingvisit) %>% 
  select( home_winter_id, adult_id_num, sampling_visit, area, cold2m:bronch2mdr)  


# Combine logs from all areas
elders_health_extra <- rbind(nn_healthextra_initial, npt_healthextra_initial) %>% 
  right_join(elders_ids_linked, c("area", "home_winter_id", "adult_id_num")) %>% 
  arrange(area, adult_id_num, winter_id, sampling_visit) %>% 
  select(area, adult_id_num, adult_id_char, home, home_id_num, home_winter_id, 
         winter_id, treatment, cold2m:bronch2mdr) %>% 
  mutate_if(is_character, as_factor)

summary(elders_health_extra)

# write_rds(elders_health_extra, paste0(file_path, "Output/elders_health_extra_clean.rds"))


save_var_names <- data.frame(t(elders_health_extra)) %>% 
  rownames_to_column() %>% 
  select(rowname)

# write_csv(save_var_names, paste0(file_path, "Output/health_extra_var_names.csv"))
```
