---
title: 'EldersAIR: Exposure-response Analysis for Health Outcomes'
author: "Ethan Walker"
date: "Started 16 April 2021; Updated 25 July 2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, eval = TRUE, include = TRUE,
                      message = FALSE, warning = FALSE)
```

```{r}
library(readxl)
library(naniar)
library(lubridate)
library(emmeans)
library(broom)
library(broom.mixed)
library(zoo)
library(car)
library(lme4)
library(lmerTest)
library(mctest)
library(tidyverse)
library(knitr)
library(kableExtra)
#library(MASS)
library(faraway)
library(splines)
library(influence.ME)
library(sjstats)
```


```{r}
# Load data

file_path <- c("C:/Users/ethan.walker/Box/Ethan Walker UM/R/EldersAIR/")

elders_cleaned_dataset_by_visit <- read_rds(paste0(file_path, "Output/elders_cleaned_dataset_by_visit.rds")) 


health_hx_data1 <- elders_cleaned_dataset_by_visit %>% 
  select(area, home, adult_id_char, winter_id, treatment, sampling_visit, age,
         rheum_arth:cigarspipes, residents_smoke, residents_smoke_inside) %>% 
  mutate_all(as.factor) %>% 
  arrange(area, home, adult_id_char, winter_id, sampling_visit) %>% 
  distinct(area, adult_id_char, .keep_all = T) %>% 
  mutate(cpd = as.character(aveperday),
         cpd = as.numeric(cpd),
         ppd = cpd/20,
         age = as.character(age),
         age = as.numeric(age),
         agequit = as.character(agequit),
         agequit = as.numeric(agequit),
         agefirst = as.character(agefirst),
         agefirst = as.numeric(agefirst),
         agequit2 = ifelse(agequit < agefirst | is.na(agequit), age, agequit),
         smoke_years = agequit2 - agefirst,
         pack_years = smoke_years*ppd)

#summary(health_hx_data)

health_hx_data_any <- health_hx_data1 %>% 
  select(area, home, adult_id_char, winter_id, sampling_visit,
         asthma, emphysema, chronicbronchitis, copd, hayfever, 
         pleuraleffusion, pleurisy, pneumonia, pneumothorax, coronaryarterydisease,
         angina, heartattack, chf, abnormalhr, pacemaker, icd, valvedisease,
         hypertension, stroke, diabetes, thyroiddisease, anemia, cancer) %>% 
  mutate(across(asthma:cancer, ~replace_na(.x, "No")))

#summary(health_hx_data_any)

health_hx_data_cvd <- health_hx_data_any %>% 
  select(area, home, adult_id_char, winter_id, sampling_visit,
         coronaryarterydisease, angina, heartattack, chf, abnormalhr, pacemaker, 
         icd, valvedisease, hypertension, stroke, anemia) 

#summary(health_hx_data_cvd)

health_hx_data_ascvd <- health_hx_data_any %>% 
  select(area, home, adult_id_char, winter_id, sampling_visit,
         coronaryarterydisease, angina, heartattack, stroke) 

#summary(health_hx_data_ascvd)

health_hx_data_resp <- health_hx_data_any %>% 
  select(area, home, adult_id_char, winter_id, sampling_visit,
         asthma, emphysema, chronicbronchitis, copd, hayfever, 
         pleuraleffusion, pleurisy, pneumonia, pneumothorax)

#summary(health_hx_data_resp)

health_hx_data <- elders_cleaned_dataset_by_visit %>% 
  select(area, home, adult_id_char, winter_id, treatment, sampling_visit,
         rheum_arth:cigarspipes, residents_smoke, residents_smoke_inside) %>% 
  mutate_all(as.factor) %>% 
  arrange(area, home, adult_id_char, winter_id, sampling_visit) %>% 
  distinct(area, adult_id_char, .keep_all = T) %>% 
  select(area, home, adult_id_char, treatment, asthma, emphysema, chronicbronchitis, copd, hayfever, 
         pleuraleffusion, pleurisy, pneumonia, pneumothorax, coronaryarterydisease,
         angina, heartattack, chf, abnormalhr, pacemaker, icd, valvedisease,
         hypertension, stroke, diabetes, thyroiddisease, anemia, cancer) %>% 
  mutate(cvd_condition = as.factor(if_else(rowSums(health_hx_data_cvd == "Yes") > 0, "Yes", "No"))) %>% 
  mutate(ascvd_condition = as.factor(if_else(rowSums(health_hx_data_ascvd == "Yes") > 0, "Yes", "No"))) %>% 
  mutate(resp_condition = as.factor(if_else(rowSums(health_hx_data_resp == "Yes") > 0, "Yes", "No"))) %>% 
  mutate(any_condition = as.factor(if_else(rowSums(health_hx_data_any == "Yes") > 0, "Yes", "No"))) %>% 
  select(area, home, adult_id_char,
         cvd_condition, ascvd_condition, resp_condition, any_condition)


analysis_data <- elders_cleaned_dataset_by_visit %>% 
  mutate(cohort = factor(cohort, levels = c("2015", "2016", "2017", "2018", "2019"))) %>% 
  mutate(bp_dia = if_else(bp_dia < 40, 9999, bp_dia),
         sp02 = if_else(sp02 < 86, 9999, sp02),
         bp_sys = if_else(bp_dia == 9999 | is.na(bp_dia), 9999, bp_sys)) %>% 
  replace_with_na(replace = list(sp02 = 9999, bp_sys = 9999, bp_dia = 9999)) %>% 
  mutate(cpd = as.character(aveperday),
         cpd = as.numeric(cpd),
         ppd = cpd/20,
         age = as.character(age),
         age = as.numeric(age),
         agequit = as.character(agequit),
         agequit = as.numeric(agequit),
         agefirst = as.character(agefirst),
         agefirst = as.numeric(agefirst),
         agequit2 = ifelse(agequit < agefirst | is.na(agequit), age, agequit),
         smoke_years = agequit2 - agefirst,
         pack_years = smoke_years*ppd) %>% 
  left_join(health_hx_data, by = c("area", "home", "adult_id_char"))

#summary(health_hx_data)
```



# Systolic BP
```{r}
## select outcome variable
### bp_sys, bp_dia, fvc, fev1, fev1_fvc_ratio, fvc_pp, fev1_pp, pm_mean_visit
er_data_4row <- analysis_data %>% 
  #filter(spiro_status == "Acceptable") %>%  # only use this filter for spiro outcomes
  mutate(outcome = bp_sys,
         sampling_date_num = as.factor(sampling_date)) %>%  # select outcome here
  arrange(area, home, adult_id_char, winter_id, sampling_visit) %>% 
  group_by(area, home, adult_id_char, winter_id, sampling_visit) %>% 
  dplyr::select(area, home, adult_id_char, winter_id, sampling_visit, 
                sampling_date_num, sampling_date, pm_mean_visit,
                cohort, treatment, outcome, income, education, residents_smoke, 
                home_sqm_2level, burn_level, gender, chimney_clean, stove_age, 
                stove_grade, age, bmi, visit_intervention_diff, 
                pm_mean_at_home_visit, mp_mean_visit,
                treatment_filter_type, filter_compliance, kw_perc_expected,
                cvd_condition, ascvd_condition, resp_condition, any_condition,
                tobuseever, tobusenow) %>% 
  mutate(pm_iqr = pm_mean_visit/32,
         pm_at_home_iqr = pm_mean_at_home_visit/32) %>% 
  ungroup() %>% 
  distinct(area, adult_id_char, winter_id, sampling_visit, .keep_all = T) 


er_results_primary <- lmer(outcome ~ pm_iqr + ns(sampling_date, df = 4) + 
                           age + gender + income + education + residents_smoke + cvd_condition + resp_condition +
                           (1 | adult_id_char:home:cohort:area), 
                           data = er_data_4row)


nobs(er_results_primary)

#isSingular(er_results_primary)

#summary(er_results_primary)

tidy_results_primary <- tidy(er_results_primary, conf.int = TRUE) %>% 
  mutate(group_filter = if_else(grepl("pm", term), 1, 0)) %>% 
  filter(group_filter == 1) %>% 
  mutate(estimate = round(estimate, digits = 2),
         conf.low = round(conf.low, digits = 2),
         conf.high = round(conf.high, digits = 2)) %>% 
  dplyr::select(term, estimate, conf.low, conf.high, p.value) %>% 
  mutate(model = "Primary") %>% 
  dplyr::select(-p.value)
kable(tidy_results_primary)


er_plot_estimates <- tidy_results_primary %>%
  ggplot() +
    geom_point(aes(x=model, y=estimate), 
               position = position_dodge(width = 0.5), size = 4) +
    geom_errorbar(aes(x=model, ymin=conf.low, ymax=conf.high), 
                  position = position_dodge(width = 0.5), size = 1.2, width = 0.5) +
    geom_hline(yintercept = 0) +
    theme_bw() +  
    ggtitle(label = "SBP and PM - ER framework") +
    labs(y = "Change in outcome per ln increase in PM") +
    labs(x = "", group = "", shape = "") +
    theme(title = element_text(size = 16), 
          axis.text.x = element_text(size = 16, colour = "black", angle = 45,
                                     hjust = 1, vjust = .8),
          axis.text.y = element_text(size = 16, colour = "black"),
          axis.title.y = element_text(size = 16,
                                      margin = margin(t = 0, r = 20, b = 0, l = 0)),
          axis.line.x = element_line(colour = "black", size = 1.2), 
          axis.line.y = element_line(colour = "black", size = 1.2), 
          axis.ticks = element_blank(), 
          panel.border = element_blank(), 
          panel.grid = element_blank(),
          legend.position = "top",
          legend.text = element_text(size = 14, colour = "black")) 
er_plot_estimates


plot(er_results_primary, main = "ER Primary Model", 
     xlab = "fitted values", ylab = "residuals")
qqnorm(residuals(er_results_primary), main = "ER Primary Model")
qqline(residuals(er_results_primary))
```

\pagebreak

# Diastolic BP
```{r}
## select outcome variable
### bp_sys, bp_dia, fvc, fev1, fev1_fvc_ratio, fvc_pp, fev1_pp, pm_mean_visit
er_data_4row <- analysis_data %>% 
  #filter(spiro_status == "Acceptable") %>%  # only use this filter for spiro outcomes
  mutate(outcome = bp_dia,
         sampling_date_num = as.factor(sampling_date)) %>%  # select outcome here
  arrange(area, home, adult_id_char, winter_id, sampling_visit) %>% 
  group_by(area, home, adult_id_char, winter_id, sampling_visit) %>% 
  dplyr::select(area, home, adult_id_char, winter_id, sampling_visit, 
                sampling_date_num, sampling_date, pm_mean_visit,
                cohort, treatment, outcome, income, education, residents_smoke, 
                home_sqm_2level, burn_level, gender, chimney_clean, stove_age, 
                stove_grade, age, bmi, visit_intervention_diff, 
                pm_mean_at_home_visit, mp_mean_visit,
                treatment_filter_type, filter_compliance, kw_perc_expected,
                cvd_condition, ascvd_condition, resp_condition, any_condition,
                tobuseever, tobusenow) %>% 
  mutate(pm_iqr = pm_mean_visit/32,
         pm_at_home_iqr = pm_mean_at_home_visit/32) %>% 
  ungroup() %>% 
  distinct(area, adult_id_char, winter_id, sampling_visit, .keep_all = T) 


er_results_primary <- lmer(outcome ~ pm_iqr + ns(sampling_date, df = 4) + 
                           age + gender + income + education + residents_smoke + cvd_condition + resp_condition +
                           (1 | adult_id_char:home:cohort:area), 
                           data = er_data_4row)

#table(model.frame(itt_results)$treatment_assigned)
nobs(er_results_primary)

#isSingular(er_results_primary)

#summary(er_results_primary)

tidy_results_primary <- tidy(er_results_primary, conf.int = TRUE) %>% 
  mutate(group_filter = if_else(grepl("pm", term), 1, 0)) %>% 
  filter(group_filter == 1) %>% 
  mutate(estimate = round(estimate, digits = 2),
         conf.low = round(conf.low, digits = 2),
         conf.high = round(conf.high, digits = 2)) %>% 
  dplyr::select(term, estimate, conf.low, conf.high, p.value) %>% 
  mutate(model = "Primary") %>% 
  dplyr::select(-p.value)
kable(tidy_results_primary)


er_plot_estimates <- tidy_results_primary %>%
  ggplot() +
    geom_point(aes(x=model, y=estimate), 
               position = position_dodge(width = 0.5), size = 4) +
    geom_errorbar(aes(x=model, ymin=conf.low, ymax=conf.high), 
                  position = position_dodge(width = 0.5), size = 1.2, width = 0.5) +
    geom_hline(yintercept = 0) +
    theme_bw() +  
    ggtitle(label = "DBP and PM - ER framework") +
    labs(y = "Change in outcome per ln increase in PM") +
    labs(x = "", group = "", shape = "") +
    theme(title = element_text(size = 16), 
          axis.text.x = element_text(size = 16, colour = "black", angle = 45,
                                     hjust = 1, vjust = .8),
          axis.text.y = element_text(size = 16, colour = "black"),
          axis.title.y = element_text(size = 16,
                                      margin = margin(t = 0, r = 20, b = 0, l = 0)),
          axis.line.x = element_line(colour = "black", size = 1.2), 
          axis.line.y = element_line(colour = "black", size = 1.2), 
          axis.ticks = element_blank(), 
          panel.border = element_blank(), 
          panel.grid = element_blank(),
          legend.position = "top",
          legend.text = element_text(size = 14, colour = "black")) 
er_plot_estimates


plot(er_results_primary, main = "ER Primary Model", 
     xlab = "fitted values", ylab = "residuals")
qqnorm(residuals(er_results_primary), main = "ER Primary Model")
qqline(residuals(er_results_primary))
```

\pagebreak

# FVC
```{r}
## select outcome variable
### bp_sys, bp_dia, fvc, fev1, fev1_fvc_ratio, fvc_pp, fev1_pp, pm_mean_visit
er_data_4row <- analysis_data %>% 
  filter(spiro_status == "Acceptable") %>%  # only use this filter for spiro outcomes
  mutate(outcome = fvc,
         sampling_date_num = as.factor(sampling_date)) %>%  # select outcome here
  arrange(area, home, adult_id_char, winter_id, sampling_visit) %>% 
  group_by(area, home, adult_id_char, winter_id, sampling_visit) %>% 
  dplyr::select(area, home, adult_id_char, winter_id, sampling_visit, 
                sampling_date_num, sampling_date, pm_mean_visit,
                cohort, treatment, outcome, income, education, residents_smoke, 
                home_sqm_2level, burn_level, gender, chimney_clean, stove_age, 
                stove_grade, age, bmi, visit_intervention_diff, 
                pm_mean_at_home_visit, mp_mean_visit,
                treatment_filter_type, filter_compliance, kw_perc_expected,
                cvd_condition, ascvd_condition, resp_condition, any_condition,
                tobuseever, tobusenow) %>% 
  mutate(pm_iqr = pm_mean_visit/32,
         pm_at_home_iqr = pm_mean_at_home_visit/32) %>% 
  ungroup() %>% 
  distinct(area, adult_id_char, winter_id, sampling_visit, .keep_all = T) 


er_results_primary <- lmer(outcome ~ pm_iqr + ns(sampling_date, df = 4) + 
                           age + gender + income + education + residents_smoke + cvd_condition + resp_condition +
                           (1 | adult_id_char:home:cohort:area), 
                           data = er_data_4row)

#table(model.frame(itt_results)$treatment_assigned)
nobs(er_results_primary)

#isSingular(er_results_primary)

#summary(er_results_primary)

tidy_results_primary <- tidy(er_results_primary, conf.int = TRUE) %>% 
  mutate(group_filter = if_else(grepl("pm", term), 1, 0)) %>% 
  filter(group_filter == 1) %>% 
  mutate(estimate = round(estimate, digits = 2),
         conf.low = round(conf.low, digits = 2),
         conf.high = round(conf.high, digits = 2)) %>% 
  dplyr::select(term, estimate, conf.low, conf.high, p.value) %>% 
  mutate(model = "Primary") %>% 
  dplyr::select(-p.value)
kable(tidy_results_primary)


er_plot_estimates <- tidy_results_primary %>%
  ggplot() +
    geom_point(aes(x=model, y=estimate), 
               position = position_dodge(width = 0.5), size = 4) +
    geom_errorbar(aes(x=model, ymin=conf.low, ymax=conf.high), 
                  position = position_dodge(width = 0.5), size = 1.2, width = 0.5) +
    geom_hline(yintercept = 0) +
    theme_bw() +  
    ggtitle(label = "FVC and PM - ER framework") +
    labs(y = "Change in outcome per ln increase in PM") +
    labs(x = "", group = "", shape = "") +
    theme(title = element_text(size = 16), 
          axis.text.x = element_text(size = 16, colour = "black", angle = 45,
                                     hjust = 1, vjust = .8),
          axis.text.y = element_text(size = 16, colour = "black"),
          axis.title.y = element_text(size = 16,
                                      margin = margin(t = 0, r = 20, b = 0, l = 0)),
          axis.line.x = element_line(colour = "black", size = 1.2), 
          axis.line.y = element_line(colour = "black", size = 1.2), 
          axis.ticks = element_blank(), 
          panel.border = element_blank(), 
          panel.grid = element_blank(),
          legend.position = "top",
          legend.text = element_text(size = 14, colour = "black")) 
er_plot_estimates


plot(er_results_primary, main = "ER Primary Model", 
     xlab = "fitted values", ylab = "residuals")
qqnorm(residuals(er_results_primary), main = "ER Primary Model")
qqline(residuals(er_results_primary))
```

\pagebreak

# FVC % Pred
```{r}
## select outcome variable
### bp_sys, bp_dia, fvc, fev1, fev1_fvc_ratio, fvc_pp, fev1_pp, pm_mean_visit
er_data_4row <- analysis_data %>% 
  filter(spiro_status == "Acceptable") %>%  # only use this filter for spiro outcomes
  mutate(outcome = fvc_pp,
         sampling_date_num = as.factor(sampling_date)) %>%  # select outcome here
  arrange(area, home, adult_id_char, winter_id, sampling_visit) %>% 
  group_by(area, home, adult_id_char, winter_id, sampling_visit) %>% 
  dplyr::select(area, home, adult_id_char, winter_id, sampling_visit, 
                sampling_date_num, sampling_date, pm_mean_visit,
                cohort, treatment, outcome, income, education, residents_smoke, 
                home_sqm_2level, burn_level, gender, chimney_clean, stove_age, 
                stove_grade, age, bmi, visit_intervention_diff, 
                pm_mean_at_home_visit, mp_mean_visit,
                treatment_filter_type, filter_compliance, kw_perc_expected) %>% 
  mutate(pm_iqr = pm_mean_visit/32,
         pm_at_home_iqr = pm_mean_at_home_visit/32) %>% 
  ungroup() %>% 
  distinct(area, adult_id_char, winter_id, sampling_visit, .keep_all = T) 


er_results_primary <- lmer(outcome ~ log(pm_mean_visit) + ns(sampling_date, df = 4) + 
                           age + gender + income + education + residents_smoke +
                           (1 | adult_id_char:home:cohort:area), 
                           data = er_data_4row)


#isSingular(er_results_primary)

#summary(er_results_primary)

tidy_results_primary <- tidy(er_results_primary, conf.int = TRUE) %>% 
  mutate(group_filter = if_else(grepl("pm", term), 1, 0)) %>% 
  filter(group_filter == 1) %>% 
  mutate(estimate = round(estimate, digits = 2),
         conf.low = round(conf.low, digits = 2),
         conf.high = round(conf.high, digits = 2)) %>% 
  dplyr::select(term, estimate, conf.low, conf.high, p.value) %>% 
  mutate(model = "Primary") %>% 
  dplyr::select(-p.value)
kable(tidy_results_primary)


er_plot_estimates <- tidy_results_primary %>%
  ggplot() +
    geom_point(aes(x=model, y=estimate), 
               position = position_dodge(width = 0.5), size = 4) +
    geom_errorbar(aes(x=model, ymin=conf.low, ymax=conf.high), 
                  position = position_dodge(width = 0.5), size = 1.2, width = 0.5) +
    geom_hline(yintercept = 0) +
    theme_bw() +  
    ggtitle(label = "FVC % Pred and PM - ER framework") +
    labs(y = "Change in outcome per ln increase in PM") +
    labs(x = "", group = "", shape = "") +
    theme(title = element_text(size = 16), 
          axis.text.x = element_text(size = 16, colour = "black", angle = 45,
                                     hjust = 1, vjust = .8),
          axis.text.y = element_text(size = 16, colour = "black"),
          axis.title.y = element_text(size = 16,
                                      margin = margin(t = 0, r = 20, b = 0, l = 0)),
          axis.line.x = element_line(colour = "black", size = 1.2), 
          axis.line.y = element_line(colour = "black", size = 1.2), 
          axis.ticks = element_blank(), 
          panel.border = element_blank(), 
          panel.grid = element_blank(),
          legend.position = "top",
          legend.text = element_text(size = 14, colour = "black")) 
er_plot_estimates


plot(er_results_primary, main = "ER Primary Model", 
     xlab = "fitted values", ylab = "residuals")
qqnorm(residuals(er_results_primary), main = "ER Primary Model")
qqline(residuals(er_results_primary))
```

\pagebreak

# FEV1
```{r}
## select outcome variable
### bp_sys, bp_dia, fvc, fev1, fev1_fvc_ratio, fvc_pp, fev1_pp, pm_mean_visit
er_data_4row <- analysis_data %>% 
  filter(spiro_status == "Acceptable") %>%  # only use this filter for spiro outcomes
  mutate(outcome = fev1,
         sampling_date_num = as.factor(sampling_date)) %>%  # select outcome here
  arrange(area, home, adult_id_char, winter_id, sampling_visit) %>% 
  group_by(area, home, adult_id_char, winter_id, sampling_visit) %>% 
  dplyr::select(area, home, adult_id_char, winter_id, sampling_visit, 
                sampling_date_num, sampling_date, pm_mean_visit,
                cohort, treatment, outcome, income, education, residents_smoke, 
                home_sqm_2level, burn_level, gender, chimney_clean, stove_age, 
                stove_grade, age, bmi, visit_intervention_diff, 
                pm_mean_at_home_visit, mp_mean_visit,
                treatment_filter_type, filter_compliance, kw_perc_expected,
                cvd_condition, ascvd_condition, resp_condition, any_condition,
                tobuseever, tobusenow) %>% 
  mutate(pm_iqr = pm_mean_visit/32,
         pm_at_home_iqr = pm_mean_at_home_visit/32) %>% 
  ungroup() %>% 
  distinct(area, adult_id_char, winter_id, sampling_visit, .keep_all = T) 


er_results_primary <- lmer(outcome ~ pm_iqr + ns(sampling_date, df = 4) + 
                           age + gender + income + education + residents_smoke + cvd_condition + resp_condition +
                           (1 | adult_id_char:home:cohort:area), 
                           data = er_data_4row)

#table(model.frame(itt_results)$treatment_assigned)
nobs(er_results_primary)

#isSingular(er_results_primary)

#summary(er_results_primary)

tidy_results_primary <- tidy(er_results_primary, conf.int = TRUE) %>% 
  mutate(group_filter = if_else(grepl("pm", term), 1, 0)) %>% 
  filter(group_filter == 1) %>% 
  mutate(estimate = round(estimate, digits = 2),
         conf.low = round(conf.low, digits = 3),
         conf.high = round(conf.high, digits = 2)) %>% 
  dplyr::select(term, estimate, conf.low, conf.high, p.value) %>% 
  mutate(model = "Primary") %>% 
  dplyr::select(-p.value)
kable(tidy_results_primary)


er_plot_estimates <- tidy_results_primary %>%
  ggplot() +
    geom_point(aes(x=model, y=estimate), 
               position = position_dodge(width = 0.5), size = 4) +
    geom_errorbar(aes(x=model, ymin=conf.low, ymax=conf.high), 
                  position = position_dodge(width = 0.5), size = 1.2, width = 0.5) +
    geom_hline(yintercept = 0) +
    theme_bw() +  
    ggtitle(label = "FEV1 and PM - ER framework") +
    labs(y = "Change in outcome per ln increase in PM") +
    labs(x = "", group = "", shape = "") +
    theme(title = element_text(size = 16), 
          axis.text.x = element_text(size = 16, colour = "black", angle = 45,
                                     hjust = 1, vjust = .8),
          axis.text.y = element_text(size = 16, colour = "black"),
          axis.title.y = element_text(size = 16,
                                      margin = margin(t = 0, r = 20, b = 0, l = 0)),
          axis.line.x = element_line(colour = "black", size = 1.2), 
          axis.line.y = element_line(colour = "black", size = 1.2), 
          axis.ticks = element_blank(), 
          panel.border = element_blank(), 
          panel.grid = element_blank(),
          legend.position = "top",
          legend.text = element_text(size = 14, colour = "black")) 
er_plot_estimates


plot(er_results_primary, main = "ER Primary Model", 
     xlab = "fitted values", ylab = "residuals")
qqnorm(residuals(er_results_primary), main = "ER Primary Model")
qqline(residuals(er_results_primary))
```

\pagebreak

# FEV1 % Pred
```{r}
## select outcome variable
### bp_sys, bp_dia, fvc, fev1, fev1_fvc_ratio, fvc_pp, fev1_pp, pm_mean_visit
er_data_4row <- analysis_data %>% 
  filter(spiro_status == "Acceptable") %>%  # only use this filter for spiro outcomes
  mutate(outcome = fev1_pp,
         sampling_date_num = as.factor(sampling_date)) %>%  # select outcome here
  arrange(area, home, adult_id_char, winter_id, sampling_visit) %>% 
  group_by(area, home, adult_id_char, winter_id, sampling_visit) %>% 
  dplyr::select(area, home, adult_id_char, winter_id, sampling_visit, 
                sampling_date_num, sampling_date, pm_mean_visit,
                cohort, treatment, outcome, income, education, residents_smoke, 
                home_sqm_2level, burn_level, gender, chimney_clean, stove_age, 
                stove_grade, age, bmi, visit_intervention_diff, 
                pm_mean_at_home_visit, mp_mean_visit,
                treatment_filter_type, filter_compliance, kw_perc_expected) %>% 
  mutate(pm_iqr = pm_mean_visit/32,
         pm_at_home_iqr = pm_mean_at_home_visit/32) %>% 
  ungroup() %>% 
  distinct(area, adult_id_char, winter_id, sampling_visit, .keep_all = T) 


er_results_primary <- lmer(outcome ~ log(pm_mean_visit) + ns(sampling_date, df = 4) + 
                           age + gender + income + education + residents_smoke +
                           (1 | adult_id_char:home:cohort:area), 
                           data = er_data_4row)


#isSingular(er_results_primary)

#summary(er_results_primary)

tidy_results_primary <- tidy(er_results_primary, conf.int = TRUE) %>% 
  mutate(group_filter = if_else(grepl("pm", term), 1, 0)) %>% 
  filter(group_filter == 1) %>% 
  mutate(estimate = round(estimate, digits = 2),
         conf.low = round(conf.low, digits = 2),
         conf.high = round(conf.high, digits = 2)) %>% 
  dplyr::select(term, estimate, conf.low, conf.high, p.value) %>% 
  mutate(model = "Primary") %>% 
  dplyr::select(-p.value)
kable(tidy_results_primary)


er_plot_estimates <- tidy_results_primary %>%
  ggplot() +
    geom_point(aes(x=model, y=estimate), 
               position = position_dodge(width = 0.5), size = 4) +
    geom_errorbar(aes(x=model, ymin=conf.low, ymax=conf.high), 
                  position = position_dodge(width = 0.5), size = 1.2, width = 0.5) +
    geom_hline(yintercept = 0) +
    theme_bw() +  
    ggtitle(label = "FEV1 % Pred and PM - ER framework") +
    labs(y = "Change in outcome per ln increase in PM") +
    labs(x = "", group = "", shape = "") +
    theme(title = element_text(size = 16), 
          axis.text.x = element_text(size = 16, colour = "black", angle = 45,
                                     hjust = 1, vjust = .8),
          axis.text.y = element_text(size = 16, colour = "black"),
          axis.title.y = element_text(size = 16,
                                      margin = margin(t = 0, r = 20, b = 0, l = 0)),
          axis.line.x = element_line(colour = "black", size = 1.2), 
          axis.line.y = element_line(colour = "black", size = 1.2), 
          axis.ticks = element_blank(), 
          panel.border = element_blank(), 
          panel.grid = element_blank(),
          legend.position = "top",
          legend.text = element_text(size = 14, colour = "black")) 
er_plot_estimates


plot(er_results_primary, main = "ER Primary Model", 
     xlab = "fitted values", ylab = "residuals")
qqnorm(residuals(er_results_primary), main = "ER Primary Model")
qqline(residuals(er_results_primary))
```

\pagebreak

# FEV1/FVC Ratio
```{r}
## select outcome variable
### bp_sys, bp_dia, fvc, fev1, fev1_fvc_ratio, fvc_pp, fev1_pp, pm_mean_visit
er_data_4row <- analysis_data %>% 
  filter(spiro_status == "Acceptable") %>%  # only use this filter for spiro outcomes
  mutate(outcome = fev1_fvc_ratio,
         sampling_date_num = as.factor(sampling_date)) %>%  # select outcome here
  arrange(area, home, adult_id_char, winter_id, sampling_visit) %>% 
  group_by(area, home, adult_id_char, winter_id, sampling_visit) %>% 
  dplyr::select(area, home, adult_id_char, winter_id, sampling_visit, 
                sampling_date_num, sampling_date, pm_mean_visit,
                cohort, treatment, outcome, income, education, residents_smoke, 
                home_sqm_2level, burn_level, gender, chimney_clean, stove_age, 
                stove_grade, age, bmi, visit_intervention_diff, 
                pm_mean_at_home_visit, mp_mean_visit,
                treatment_filter_type, filter_compliance, kw_perc_expected,
                cvd_condition, ascvd_condition, resp_condition, any_condition,
                tobuseever, tobusenow) %>% 
  mutate(pm_iqr = pm_mean_visit/32,
         pm_at_home_iqr = pm_mean_at_home_visit/32) %>% 
  ungroup() %>% 
  distinct(area, adult_id_char, winter_id, sampling_visit, .keep_all = T) 


er_results_primary <- lmer(outcome ~ pm_iqr + ns(sampling_date, df = 4) + 
                           age + gender + income + education + residents_smoke + cvd_condition + resp_condition +
                           (1 | adult_id_char:home:cohort:area), 
                           data = er_data_4row)

#table(model.frame(itt_results)$treatment_assigned)
nobs(er_results_primary)

#isSingular(er_results_primary)

#summary(er_results_primary)

tidy_results_primary <- tidy(er_results_primary, conf.int = TRUE) %>% 
  mutate(group_filter = if_else(grepl("pm", term), 1, 0)) %>% 
  filter(group_filter == 1) %>% 
  mutate(estimate = round(estimate, digits = 2),
         conf.low = round(conf.low, digits = 2),
         conf.high = round(conf.high, digits = 2)) %>% 
  dplyr::select(term, estimate, conf.low, conf.high, p.value) %>% 
  mutate(model = "Primary") 
kable(tidy_results_primary)


er_plot_estimates <- tidy_results_primary %>%
  ggplot() +
    geom_point(aes(x=model, y=estimate), 
               position = position_dodge(width = 0.5), size = 4) +
    geom_errorbar(aes(x=model, ymin=conf.low, ymax=conf.high), 
                  position = position_dodge(width = 0.5), size = 1.2, width = 0.5) +
    geom_hline(yintercept = 0) +
    theme_bw() +  
    ggtitle(label = "FEV1/FVC Ratio and PM - ER framework") +
    labs(y = "Change in outcome per ln increase in PM") +
    labs(x = "", group = "", shape = "") +
    theme(title = element_text(size = 16), 
          axis.text.x = element_text(size = 16, colour = "black", angle = 45,
                                     hjust = 1, vjust = .8),
          axis.text.y = element_text(size = 16, colour = "black"),
          axis.title.y = element_text(size = 16,
                                      margin = margin(t = 0, r = 20, b = 0, l = 0)),
          axis.line.x = element_line(colour = "black", size = 1.2), 
          axis.line.y = element_line(colour = "black", size = 1.2), 
          axis.ticks = element_blank(), 
          panel.border = element_blank(), 
          panel.grid = element_blank(),
          legend.position = "top",
          legend.text = element_text(size = 14, colour = "black")) 
er_plot_estimates


plot(er_results_primary, main = "ER Primary Model", 
     xlab = "fitted values", ylab = "residuals")
qqnorm(residuals(er_results_primary), main = "ER Primary Model")
qqline(residuals(er_results_primary))
```



