---
title: "Elders home characteristics/activity summary"
author: "Ethan Walker"
date: "Started 5 March 2020, Updated 10 March 2020"
output:
  pdf_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, eval = TRUE, 
                      include = TRUE, warning = FALSE)
```

```{r, message=FALSE}
library(tidyverse)
library(readr)
library(knitr)
library(readxl)
jv_palette <- c("#330099","#CC0066","#FF6633", 
                 "#0099CC", "#FF9900","#CC6633",
                  "#FF3366", "#33CC99", "#33999")
```

```{r}
# Load dataset
home_char_clean <- read_rds("Output/elders_home_char_clean.rds")
home_act_clean <- read_rds("Output/elders_home_activity_clean.rds")
elders_ids_linked <- read_rds("Output/elders_ids_linked.rds")
elders_pm <- read_rds("Output/elders_pm_clean.rds")
```

# Summary data for home characteristics
```{r}
# Summarize numeric vars: home_sqft, home_year_built, home_bedrooms, home_windows,
# home_pets, home_furry, wood_cords
home_char_summary <- home_char_clean %>% 
  filter(winter_id == 1) %>% 
  distinct(home, .keep_all = TRUE) %>% 
  #group_by(area) %>% 
  summarize("N" = n(),
            "Mean" = mean(wood_cords, na.rm = TRUE), 
            "SD" = sd(wood_cords, na.rm = TRUE), 
            "Min" = min(wood_cords, na.rm = TRUE), 
            "Median" = median(wood_cords, na.rm = TRUE), 
            "Max" = max(wood_cords, na.rm = TRUE))
kable(home_char_summary, digits = 1, align = "c")

# Summarize factor vars
## Use this as a quick look at all vars
table_list <- home_char_clean %>%  
  filter(winter_id == 1) %>%  
  distinct(home, .keep_all = TRUE) %>% 
  #filter(area == "WMT") %>% 
  select(area, residents_smoke, residents_smoke_inside, home_type, home_floors,
         primary_heat, secondary_heat, stove_age, stove_cert, wood_collect,
         wood_collect_method, chimney_clean, home_damp, home_mold, home_fireplace,
         home_furnace, home_woodstove)
#lapply(table_list, table)

## Select specific var to assess individually/group by area
table(table_list$area, table_list$wood_collect_method, useNA = "ifany")

table(table_list$wood_collect_method, useNA = "ifany")
```

# Summary data for home activity
```{r}
# Summarize factor vars
## Use this as a quick look at all vars
table_list <- home_act_clean %>% 
  filter(winter_id == 1) %>% 
  select(area, home_act_elect, home_act_gas, home_act_oil, home_act_other,
         home_act_propane, home_act_smoking, home_act_incense, home_act_candle,
         home_act_kerosene, home_act_windows, home_act_door, home_act_sweep) 
  #lapply(table_list, table)


## Select specific var to assess individually/group by area
table(table_list$area, table_list$home_act_elect, useNA = "ifany")

table(table_list$home_furnace, useNA = "ifany")
```

# Home characteristics summary plots
```{r}
home_char_function <- function(data, variable) {

home_plot <- data %>% 
  filter(winter_id == 1) %>% 
  select(area, variable) %>% 
  rename(plot_var = variable) %>% 
  #na.exclude() %>% 
  ggplot() +
    geom_bar(aes(plot_var, fill = area)) +
    theme_minimal() +
    labs(title = variable) +
    theme(axis.text.x = element_text(size = 16, colour = "black", 
                                     angle = 40, vjust = 0.7, hjust = 0.7),
          axis.text.y = element_text(size = 16, colour = "black"),
          title = element_text(size = 18, colour = "black"),
          legend.text = element_text(size = 14, colour = "black"),
          legend.title = element_text(size = 16, colour = "black"),
          axis.title.y = element_blank(),
          axis.title.x = element_blank(),
          axis.line.x = element_line(colour = "black", size = 1.2), 
          axis.line.y = element_line(colour = "black", size = 1.2), 
          axis.ticks = element_blank(),
          panel.grid = element_blank()) +
    scale_fill_manual(values = jv_palette)
home_plot

}

home_char_function(home_char_clean, "residents_total")
home_char_function(home_char_clean, "residents_over55")
home_char_function(home_char_clean, "residents_under18")
home_char_function(home_char_clean, "residents_smoke")
home_char_function(home_char_clean, "residents_smoke_inside")
home_char_function(home_char_clean, "home_type")
home_char_function(home_char_clean, "home_floors")
home_char_function(home_char_clean, "home_windows")
home_char_function(home_char_clean, "home_bedrooms")
home_char_function(home_char_clean, "home_pets")
home_char_function(home_char_clean, "home_furry")
home_char_function(home_char_clean, "primary_heat")
home_char_function(home_char_clean, "secondary_heat")
home_char_function(home_char_clean, "stove_age")
home_char_function(home_char_clean, "stove_cert")
home_char_function(home_char_clean, "chimney_clean")
home_char_function(home_char_clean, "home_mold")
home_char_function(home_char_clean, "home_damp")
home_char_function(home_char_clean, "home_fireplace")
home_char_function(home_char_clean, "home_furnace")
home_char_function(home_char_clean, "home_woodstove")
home_char_function(home_char_clean, "home_insert")
```

# Home activity summary plots
```{r}
home_act_function <- function(data, variable) {

home_plot <- data %>% 
  filter(winter_id == 1) %>% 
  select(area, variable) %>% 
  rename(plot_var = variable) %>% 
  #na.exclude() %>% 
  ggplot() +
    geom_bar(aes(plot_var, fill = area)) +
    theme_minimal() +
    labs(title = variable) +
    theme(axis.text.x = element_text(size = 16, colour = "black", 
                                     angle = 40, vjust = 0.7, hjust = 0.7),
          axis.text.y = element_text(size = 16, colour = "black"),
          title = element_text(size = 18, colour = "black"),
          legend.text = element_text(size = 14, colour = "black"),
          legend.title = element_text(size = 16, colour = "black"),
          axis.title.y = element_blank(),
          axis.title.x = element_blank(),
          axis.line.x = element_line(colour = "black", size = 1.2), 
          axis.line.y = element_line(colour = "black", size = 1.2), 
          axis.ticks = element_blank(),
          panel.grid = element_blank()) +
    scale_fill_manual(values = jv_palette)
home_plot

}

home_act_function(home_act_clean, "home_act_gas")
home_act_function(home_act_clean, "home_act_elect")
home_act_function(home_act_clean, "home_act_propane")
home_act_function(home_act_clean, "home_act_oil")
home_act_function(home_act_clean, "home_act_smoking")
home_act_function(home_act_clean, "home_act_incense")
home_act_function(home_act_clean, "home_act_candle")
home_act_function(home_act_clean, "home_act_kerosene")
home_act_function(home_act_clean, "home_act_windows")
home_act_function(home_act_clean, "home_act_door")
home_act_function(home_act_clean, "home_act_sweep")
```

#### Abstract/manuscript tables ####

# Filter for homes that have PM data
```{r}
# 93 Winter 1 placebo homes have PM data
pm_homes_placebo <- pm_clean %>% 
  filter(winter_id == 1) %>% 
  filter(treatment == "Placebo") %>% 
  group_by(area, home) %>% 
  mutate(initial_obs = if_else(pm_datetime_new == first_datetime_new, 1, 0)) %>% 
  filter(initial_obs == 1) %>% 
  mutate(pm_home = "true") %>% 
  select(area, home, home_winter_id, pm_home) %>% 
  ungroup() %>% 
  arrange(area, home)

home_char_filtered <- home_char_clean %>% 
  # change to correct joining data of interest
  left_join(pm_homes_placebo, by = c("area", "home", "home_winter_id")) %>% 
  filter(pm_home == "true") %>% 
  filter(winter_id == 1) %>% 
  ungroup() %>% 
  arrange(area, home)

home_act_filtered <- home_act_clean %>% 
  # change to correct joining data of interest
  left_join(pm_homes_placebo, by = c("area", "home", "home_winter_id")) %>% 
  filter(pm_home == "true") %>% 
  filter(winter_id == 1) %>% 
  ungroup() %>% 
  arrange(area, home)
```

# Summarize home data
```{r}
# Summarize numeric vars
kids_char <- home_char_filtered %>%  
  distinct(home, .keep_all = TRUE) %>%  
  group_by(area) %>% 
  summarize("Mean" = mean(home_furry, na.rm = TRUE), 
            "SD" = sd(home_furry, na.rm = TRUE),
            "min" = min(home_furry, na.rm = TRUE), 
            "max" = max(home_furry, na.rm = TRUE))
kable(kids_char, digits = 1, align = "c")


home_char_filtered %>% 
  count(stove_age)


# Summarize factor vars
alaska_char <- home_act_filtered %>%  
  #distinct(home, .keep_all = TRUE) %>% 
  filter(area == "AK") %>% 
  group_by(home_act_sweep) %>% 
  #summarize(n = n(), percent = (n()/10)*100)
  summarize(n = n(), percent = (n()/60)*100)
alaska_char

navajo_char <- home_act_filtered %>%  
  #distinct(home, .keep_all = TRUE) %>% 
  filter(area == "NN") %>% 
  group_by(home_act_sweep) %>% 
  #summarize(n = n(), percent = (n()/23)*100)
  summarize(n = n(), percent = (n()/138)*100)
navajo_char

montana_char <- home_act_filtered %>%  
  #distinct(home, .keep_all = TRUE) %>% 
  filter(area == "WMT") %>% 
  group_by(home_act_sweep) %>% 
  #summarize(n = n(), percent = (n()/60)*100)
  summarize(n = n(), percent = (n()/360)*100)
montana_char

kids_char <- rbind(alaska_char, navajo_char, montana_char)
kids_char
```

