---
title: "Elders indoor temp/RH summary"
author: "Ethan Walker"
date: "Started 5 March 2020, Updated 12 March 2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, eval = TRUE, 
                      include = TRUE, warning = FALSE)
```

```{r, message=FALSE}
library(tidyverse)
library(readr)
library(knitr)
```

```{r}
file_path <- c("C:/Users/ethan.walker/Box/Ethan Walker UM/R/EldersAIR/")

# Load data
indoor_temp_rh_clean <- read_rds(paste0(file_path, "Output/elders_temp_rh_clean.rds"))
elders_ids_linked <- read_rds(paste0(file_path, "Output/elders_ids_linked.rds"))
```


```{r, include=FALSE}
# Summary stats

temp_rh_summary <- indoor_temp_rh_clean %>%
  filter(winter_id == 1) %>% 
  group_by(area) %>% 
  summarize_if(is.numeric, list(mean = mean, sd = sd, min = min, 
                                med = median, max = max), na.rm = TRUE) %>% 
  select(-area) %>% 
  t() 
kable(temp_rh_summary, col.names = c("Navajo", "Nez Perce"), 
      digits = 1, align = "c")


temp_rh_n <- indoor_temp_rh_clean %>% 
  filter(winter_id == 1) %>% 
  group_by(area, home) %>%
  filter(!is.na(temp_indoor_current)) %>% 
  distinct(home, .keep_all = TRUE) %>% 
  count()
```


```{r}
temp_rh_summary_function <- function(data, var, title_label, y_label) {
  
  temp_rh_summary <- data %>% 
    filter(winter_id == 1) %>% 
    #select(var) %>% 
    select(area, var) %>% 
    group_by(area) %>% 
    summarize_all(list(mean=mean, sd=sd, min=min, med=median, max=max), na.rm = TRUE)
  temp_rh_summary <<- temp_rh_summary
  
  temp_rh_summary_plot <- data %>% 
    filter(winter_id == 1) %>% 
    select(area, var) %>% 
    rename(plot_var = var) %>% 
    filter(!is.na(plot_var)) %>% 
    ggplot(aes(area, plot_var)) +
    geom_boxplot(aes(size = 1), lwd = 1.2, colour = "black", 
               fatten = 1, outlier.size = 1.5, width = 0.35) +
    stat_summary(fun.y=mean, geom="point", shape=17, size=4, color="red",
                 position=position_nudge(x = -0.1, y = 0)) +
    stat_summary(aes(label=round(..y.., digits = 1)), fun.y=mean, geom="text", 
                 size=7, position=position_nudge(x = -0.35, y = 0)) +
    stat_summary(fun.y=median, geom="point", shape=16, size=4, color="blue",
                 position=position_nudge(x = 0.1, y = 0)) +
    stat_summary(aes(label=round(..y.., digits = 1)), fun.y=median, geom="text", 
                 size=7, position=position_nudge(x = 0.35, y = 0)) +
    theme_minimal() +
    labs(title = title_label, subtitle = "Mean = Red, Median = Blue") +
    ylab(y_label) +
    theme(title = element_text(size = 20, colour = "black"),
          axis.text.x = element_text(size = 16, colour = "black"),
          axis.text.y = element_text(size = 16, colour = "black"),
          axis.title.y = element_text(size = 16, colour = "black"),
          axis.title.x = element_blank(),
          axis.line.x = element_line(colour = "black", size = 1.2), 
          axis.line.y = element_line(colour = "black", size = 1.2), 
          axis.ticks = element_blank()) 
  temp_rh_summary_plot
  
}

temp_rh_summary_function(indoor_temp_rh_clean, "temp_indoor_current", "Current indoor temp", "degrees C")
temp_rh_summary_function(indoor_temp_rh_clean, "temp_indoor_min", "Min indoor temp", "degrees C")
temp_rh_summary_function(indoor_temp_rh_clean, "temp_indoor_max", "Max indoor temp", "degrees C")
temp_rh_summary_function(indoor_temp_rh_clean, "rh_indoor_current", "Current indoor RH", "%")
temp_rh_summary_function(indoor_temp_rh_clean, "rh_indoor_min", "Min indoor RH", "%")
temp_rh_summary_function(indoor_temp_rh_clean, "rh_indoor_max", "Max indoor RH", "%")
```


