---
title: "EldersAIR initial temp/rh data work"
author: "Ethan Walker"
date: "Started 14 Feb 2020, Updated 25 Feb 2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE}
library(tidyverse)
library(readxl)
library(naniar)
library(lubridate)
library(zoo)
```

```{r}
file_path <- c("C:/Users/ethan.walker/Box/Ethan Walker UM/R/EldersAIR/")
```


# Load, format, and save indoor temp/rh data
```{r}
## Box location: Update Box location once final data loaded
np_temp_rh_initial <- read_xlsx(paste0(file_path, "Input/NP/np_qtrack_20200225.xlsx")) %>% 
  # rename variables
  mutate(home_winter_id = factor(HomeWinterID),
         rh_indoor_current = as.numeric(RelHumCur),
         rh_indoor_max = as.numeric(RelHumMax),
         rh_indoor_min = as.numeric(RelHumMin),
         temp_indoor_current = as.numeric(TempCCur),
         temp_indoor_max = as.numeric(TempCMax),
         temp_indoor_min = as.numeric(TempCMin),
         sampling_visit = factor(SamplingVisit),
         area = "NP") %>% 
  # replace -999 and 0 values with NA
  replace_with_na(replace = list(rh_indoor_current = -999, rh_indoor_max = -999,
                                 rh_indoor_min = -999, temp_indoor_current = -999,
                                 temp_indoor_max = -999, temp_indoor_min = -999)) %>% 
  replace_with_na(replace = list(rh_indoor_current = 0, rh_indoor_max = 0,
                                 rh_indoor_min = 0, temp_indoor_current = 0,
                                 temp_indoor_max = 0, temp_indoor_min = 0)) %>% 
  select(home_winter_id, area, rh_indoor_current, 
         rh_indoor_max, rh_indoor_min, temp_indoor_current, 
         temp_indoor_max, temp_indoor_min, sampling_visit) %>% 
  arrange(home_winter_id)


## Box location: Update Box location once final data loaded
nn_temp_rh_initial <- read_xlsx(paste0(file_path, "Input/NN/nn_qtrack_20200225.xlsx")) %>% 
  # rename variables
  mutate(home_winter_id = factor(HomeWinterID),
         rh_indoor_current = as.numeric(RelHumCur),
         rh_indoor_max = as.numeric(RelHumMax),
         rh_indoor_min = as.numeric(RelHumMin),
         temp_indoor_current = as.numeric(TempCCur),
         temp_indoor_max = as.numeric(TempCMax),
         temp_indoor_min = as.numeric(TempCMin),
         sampling_visit = factor(SamplingVisit),
         area = "NN") %>% 
  # replace -999 and 0 values with NA
  replace_with_na(replace = list(rh_indoor_current = -999, rh_indoor_max = -999,
                                 rh_indoor_min = -999, temp_indoor_current = -999,
                                 temp_indoor_max = -999, temp_indoor_min = -999)) %>% 
  replace_with_na(replace = list(rh_indoor_current = 0, rh_indoor_max = 0,
                                 rh_indoor_min = 0, temp_indoor_current = 0,
                                 temp_indoor_max = 0, temp_indoor_min = 0)) %>% 
  select(home_winter_id, area, rh_indoor_current, 
         rh_indoor_max, rh_indoor_min, temp_indoor_current, 
         temp_indoor_max, temp_indoor_min, sampling_visit) %>% 
  arrange(home_winter_id)


# Combine locations and save
elders_temp_rh <- rbind(np_temp_rh_initial, nn_temp_rh_initial)

#write_rds(elders_temp_rh, paste0(file_path, "Output/elders_temp_rh.rds"))
```



# Clean up all temp/rh data
```{r}
elders_temp_rh <- read_rds(paste0(file_path, "Output/elders_temp_rh.rds"))

elders_ids_linked <- read_rds(paste0(file_path, "Output/elders_ids_linked.rds"))

elders_temp_rh_clean <- elders_temp_rh %>% 
  left_join(elders_ids_linked, by = c("area", "home_winter_id")) %>% 
  filter(!is.na(home_winter_id))
# write_rds(elders_temp_rh_clean, paste0(file_path, "Output/elders_temp_rh_clean.rds"))

elders_temp_rh_clean <- read_rds(paste0(file_path, "Output/elders_temp_rh_clean.rds"))
```

