---
title: 'EldersAIR: Main analysis - PM/Exposure Outcomes'
author: "Ethan Walker"
date: "Started 6 May 2021; Updated 7 September 2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, eval = TRUE, include = TRUE,
                      message = FALSE, warning = FALSE)
```

```{r}
library(readxl)
library(naniar)
library(lubridate)
library(emmeans)
library(broom)
library(broom.mixed)
library(zoo)
library(car)
library(lme4)
library(lmerTest)
library(mctest)
library(tidyverse)
library(knitr)
library(kableExtra)
#library(MASS)
library(faraway)
library(splines)
library(influence.ME)
library(sjstats)
```

```{r}
# Load data

file_path <- c("C:/Users/ethan.walker/Box/Ethan Walker UM/R/EldersAIR/")

analysis_data <- read_rds(paste0(file_path, "Output/elders_cleaned_dataset_by_visit.rds")) %>% 
  mutate(cohort = factor(cohort, levels = c("2015", "2016", "2017", "2018", "2019"))) 
#  select(home, mp_mean_winter, pm_mean_winter) %>% 
#  arrange(desc(mp_mean_winter))
#head(analysis_data)

cbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", 
               "#0072B2", "#D55E00", "#CC79A7")
```


# Stratify some covariates by study area and winter
```{r}
table_data <- analysis_data %>% 
  filter(!is.na(pm_mean_winter)) %>% 
  distinct(area, home, winter_id, .keep_all = T)


table(table_data$wood_collect_method, table_data$area, table_data$winter_id)

table(table_data$wood_collect_3level, table_data$area, table_data$winter_id)

table(table_data$stove_grade, table_data$area, table_data$winter_id)

table(table_data$residents_smoke, table_data$area, table_data$winter_id)

table(table_data$burn_level_3level, table_data$area, table_data$winter_id)

table(table_data$stove_age_2level, table_data$area, table_data$winter_id)

summary_data <- analysis_data %>% 
  group_by(area, winter_id, wood_collect_3level) %>% 
  summarize(`Mean Moisture` = mean(moisture_ave, na.rm = T),
            `Median Moisture` = median(moisture_ave, na.rm = T))
summary_data
```


# Indoor/Area PM2.5
```{r}
# Prep data for primary analysis - 1 row per winter
pm_data_2row <- analysis_data %>%
  #filter(area == "NPT") %>% 
  mutate(outcome = pm_mean_visit) %>%  # select outcome here
  arrange(area, home, adult_id_char, winter_id, sampling_visit) %>% 
  group_by(area, home, adult_id_char, winter_id) %>% 
  mutate(outcome = if_else(winter_id == 1, mean(outcome, na.rm = T), outcome)) %>% 
  dplyr::select(area, home, adult_id_char, winter_id, sampling_visit, 
                cohort, treatment, outcome, income, education, residents_smoke, 
                home_sqm_2level, burn_level, gender, chimney_clean, stove_age, 
                stove_grade, age, bmi, visit_intervention_diff,
                treatment_filter_type, filter_compliance, kw_perc_expected,
                burn_level_3level, chimney_clean_3level, age_2level,
                bmi_2level, income_2level, income_3level, stove_age_2level,
                steps, steps_2level, steps_4level, moisture_ave, sums_winter_mean,
                hypertension, wood_collect_3level) %>% 
  ungroup() %>% 
  distinct(area, home, winter_id, sampling_visit, .keep_all = T) %>% 
  group_by(area, home) %>% 
  pivot_wider(names_from = "winter_id", values_from = "outcome") %>% 
  arrange(area, home, sampling_visit) %>% 
  mutate(outcome = `2`,
         baseline_outcome = `1`,
         baseline_outcome = if_else(is.na(baseline_outcome), first(baseline_outcome),
                                    baseline_outcome)) %>% 
  replace_with_na(replace = list(baseline_outcome = NaN, outcome = NaN)) %>% 
  filter(visit_intervention_diff != 9999) %>% 
  #filter(home != "NPE5301") %>% 
  ungroup()


# Prep data for sensitivity analysis - at-home PM data
pm_at_home_data <- analysis_data %>% 
  mutate(outcome = pm_mean_at_home_visit) %>%  # select outcome here
  arrange(area, home, adult_id_char, winter_id, sampling_visit) %>% 
  group_by(area, home, adult_id_char, winter_id) %>% 
  mutate(outcome = if_else(winter_id == 1, mean(outcome, na.rm = T), outcome)) %>% 
  dplyr::select(area, home, adult_id_char, winter_id, sampling_visit, 
                cohort, treatment, outcome, income, education, residents_smoke, 
                home_sqm_2level, burn_level, gender, chimney_clean, stove_age, 
                stove_grade, age, bmi, visit_intervention_diff,
                treatment_filter_type, filter_compliance, kw_perc_expected,
                burn_level_3level, chimney_clean_3level, age_2level,
                bmi_2level, income_2level, income_3level, stove_age_2level,
                steps, steps_2level, steps_4level, moisture_ave,
                hypertension, wood_collect_3level) %>% 
  ungroup() %>% 
  distinct(area, adult_id_char, winter_id, sampling_visit, .keep_all = T) %>% 
  group_by(area, adult_id_char) %>% 
  pivot_wider(names_from = "winter_id", values_from = "outcome") %>% 
  arrange(area, adult_id_char, sampling_visit) %>% 
  mutate(outcome = `2`,
         baseline_outcome = `1`,
         baseline_outcome = if_else(is.na(baseline_outcome), first(baseline_outcome),
                                    baseline_outcome)) %>% 
  replace_with_na(replace = list(baseline_outcome = NaN, outcome = NaN)) %>% 
  filter(visit_intervention_diff != 9999) %>% 
  #filter(home != "NPE5301") %>% 
  ungroup()


# Run primary model
itt_pm_results_primary <- lmer(log(outcome) ~ treatment + 
                                baseline_outcome + (1 | home:cohort:area), 
                                data = pm_data_2row)

# Number of observations in analysis by treatment
table(model.frame(itt_pm_results_primary)$treatment)

# Number of total observations in analysis
nobs(itt_pm_results_primary)

# Check if model is overfit
#isSingular(itt_pm_results_primary)

#summary(itt_pm_results_primary)

tidy_results_primary <- tidy(itt_pm_results_primary, conf.int = TRUE) %>% 
  mutate(group_filter = if_else(grepl("treatment", term), 1, 0)) %>% 
  filter(group_filter == 1) %>% 
  mutate(term = gsub("treatment", "", term)) %>% 
  mutate(estimate = round((exp(estimate)-1)*100, digits = 2),
         conf.low = round((exp(conf.low)-1)*100, digits = 2),
         conf.high = round((exp(conf.high)-1)*100, digits = 2),
         p.value = round((p.value), digits = 2)) %>% 
  dplyr::select(term, estimate, conf.low, conf.high, p.value) %>% 
  mutate(term = gsub("treatment", "", term),
         model = "Primary") 
kable(tidy_results_primary)


# Run model with at-home PM data
itt_pm_results_athome <- lmer(log(outcome) ~ treatment + 
                                baseline_outcome + (1 | adult_id_char:home:cohort:area), 
                                data = pm_at_home_data)

nobs(itt_pm_results_athome)


tidy_results_athome <- tidy(itt_pm_results_athome, conf.int = TRUE) %>% 
  mutate(group_filter = if_else(grepl("treatment", term), 1, 0)) %>% 
  filter(group_filter == 1) %>% 
  mutate(term = gsub("treatment", "", term)) %>% 
  mutate(estimate = round((exp(estimate)-1)*100, digits = 2),
         conf.low = round((exp(conf.low)-1)*100, digits = 2),
         conf.high = round((exp(conf.high)-1)*100, digits = 2),
         p.value = round((p.value), digits = 2)) %>% 
  dplyr::select(term, estimate, conf.low, conf.high, p.value) %>% 
  mutate(term = gsub("treatment", "", term),
         model = "At-home PM2.5") 


# Run model using filter type instead of filter as primary treatment variable
itt_pm_results_filter_type <- lmer(log(outcome) ~ treatment_filter_type + 
                                baseline_outcome + (1 | home:cohort:area), 
                                data = pm_data_2row)

table(model.frame(itt_pm_results_filter_type)$treatment_filter_type)

nobs(itt_pm_results_filter_type)


tidy_results_filter_type <- tidy(itt_pm_results_filter_type, conf.int = TRUE) %>% 
  mutate(group_filter = if_else(grepl("treatment", term), 1, 0)) %>% 
  filter(group_filter == 1) %>% 
  mutate(term = gsub("treatment_filter_type", "", term)) %>% 
  mutate(estimate = round((exp(estimate)-1)*100, digits = 2),
         conf.low = round((exp(conf.low)-1)*100, digits = 2),
         conf.high = round((exp(conf.high)-1)*100, digits = 2),
         p.value = round((p.value), digits = 2)) %>% 
  dplyr::select(term, estimate, conf.low, conf.high, p.value) %>% 
  mutate(model = "Filter Type") 


# Run model with filter compliance instead of filter as primary treatment variable
itt_pm_results_filter_compliance <- lmer(log(outcome) ~ filter_compliance + 
                                baseline_outcome + (1 | home:cohort:area), 
                                data = pm_data_2row)

test <- pm_data_2row %>% 
  select(area, home, filter_compliance, outcome) %>% 
  group_by(area, filter_compliance) %>% 
  summarise(median(outcome, na.rm = T))

test2 <- analysis_data %>% 
  filter(treatment == "Filter")


tidy_results_filter_compliance <- tidy(itt_pm_results_filter_compliance, conf.int = TRUE) %>% 
  mutate(group_filter = if_else(grepl("filter_compliance", term), 1, 0)) %>% 
  filter(group_filter == 1) %>% 
  mutate(term = gsub("filter_compliance", "", term)) %>% 
  mutate(estimate = round((exp(estimate)-1)*100, digits = 2),
         conf.low = round((exp(conf.low)-1)*100, digits = 2),
         conf.high = round((exp(conf.high)-1)*100, digits = 2),
         p.value = round((p.value), digits = 2)) %>% 
  dplyr::select(term, estimate, conf.low, conf.high, p.value) %>% 
  mutate(model = "Filter Compliance") 


# Run sensitivity analysis - primary model with inclusion of potential confounders
itt_pm_results_confounders <- lmer(log(outcome) ~ treatment + 
                                education + residents_smoke + home_sqm_2level +
                                burn_level_3level + gender + chimney_clean_3level + 
                                stove_grade + age + moisture_ave + 
                                baseline_outcome + (1 | home:cohort:area), 
                                data = pm_data_2row)

nobs(itt_pm_results_confounders)


tidy_results_confounders <- tidy(itt_pm_results_confounders, conf.int = TRUE) %>% 
  mutate(group_filter = if_else(grepl("treatment", term), 1, 0)) %>% 
  filter(group_filter == 1) %>% 
  mutate(term = gsub("treatment", "", term)) %>% 
  mutate(estimate = round((exp(estimate)-1)*100, digits = 2),
         conf.low = round((exp(conf.low)-1)*100, digits = 2),
         conf.high = round((exp(conf.high)-1)*100, digits = 2),
         p.value = round((p.value), digits = 2)) %>% 
  dplyr::select(term, estimate, conf.low, conf.high, p.value) %>% 
  mutate(term = gsub("treatment", "", term),
         model = "Adjusted")


# Calculate ICC
## The ratio of the between-cluster variance to the total variance
## It can also be interpreted as the correlation among observations within the same cluster
icc_model <- lmer(outcome ~ (1 | home), pm_data_2row)
pm_icc <- icc(icc_model)


# Combine tidy results from various analyses above
tidy_results_combined <- rbind(tidy_results_primary, tidy_results_filter_type,
                               #tidy_results_filter_compliance, 
                               tidy_results_athome, tidy_results_confounders)
kable(tidy_results_primary)


# Plot analysis results
itt_plot_estimates <- tidy_results_combined %>%
  mutate(model = factor(model,
                        levels = c("Primary", "Filter Type", "At-home PM2.5",
                                   #"Filter Compliance", 
                                   "Adjusted"))) %>% 
  ggplot(aes(group = term, shape = term)) +
    geom_point(aes(x=model, y=estimate), 
               position = position_dodge(width = 0.5), size = 4) +
    geom_errorbar(aes(x=model, ymin=conf.low, ymax=conf.high), 
                  position = position_dodge(width = 0.5), size = 1.2, width = 0.5) +
    geom_hline(yintercept = 0) +
    theme_bw() +  
    #ggtitle(label = "PM Model - ITT framework",
     #       subtitle = "ICC for Household = 0.42") +
    labs(y = "Percent difference \ncompared to Placebo") +
    labs(x = "", group = "", shape = "") +
    scale_y_continuous(breaks = c(seq(-150, 150, 10)), labels = c(seq(-150, 150, 10))) +
    theme(title = element_text(size = 16), 
          axis.text.x = element_text(size = 16, colour = "black", angle = 45,
                                     hjust = 1, vjust = .8),
          axis.text.y = element_text(size = 16, colour = "black"),
          axis.title.y = element_text(size = 16,
                                      margin = margin(t = 0, r = 20, b = 0, l = 0)),
          axis.line.x = element_line(colour = "black", size = 1.2), 
          axis.line.y = element_line(colour = "black", size = 1.2), 
          axis.ticks = element_blank(), 
          panel.border = element_blank(), 
          panel.grid = element_blank(),
          legend.position = "top",
          legend.text = element_text(size = 14, colour = "black")) 
itt_plot_estimates

#ggsave("itt_plot_estimates.jpg", width = 12, height = 6)


# Plot primary model diagnostic plots
plot(itt_pm_results_primary, main = "ITT Primary Model", 
     xlab = "fitted values", ylab = "residuals")
qqnorm(residuals(itt_pm_results_primary), main = "ITT Primary Model")
qqline(residuals(itt_pm_results_primary))

# Plot analysis results
itt_plot_estimates <- tidy_results_primary %>%
  ggplot(aes(group = term, shape = term)) +
    geom_point(aes(x=model, y=estimate), 
               position = position_dodge(width = 0.5), size = 4) +
    geom_errorbar(aes(x=model, ymin=conf.low, ymax=conf.high), 
                  position = position_dodge(width = 0.5), size = 1.2, width = 0.5) +
    geom_hline(yintercept = 0) +
    theme_bw() +  
    #ggtitle(label = "PM Model - ITT framework",
     #       subtitle = "ICC for Household = 0.42") +
    labs(y = "Percent difference \ncompared to Placebo") +
    labs(x = "", group = "", shape = "") +
    scale_y_continuous(breaks = c(seq(-150, 150, 10)), labels = c(seq(-150, 150, 10))) +
    theme(title = element_text(size = 16), 
          axis.text.x = element_blank(),
          axis.text.y = element_text(size = 16, colour = "black"),
          axis.title.y = element_text(size = 16,
                                      margin = margin(t = 0, r = 20, b = 0, l = 0)),
          axis.line.x = element_line(colour = "black", size = 1.2), 
          axis.line.y = element_line(colour = "black", size = 1.2), 
          axis.ticks = element_blank(), 
          panel.border = element_blank(), 
          panel.grid = element_blank(),
          legend.position = "top",
          legend.text = element_text(size = 14, colour = "black")) 
itt_plot_estimates

#ggsave("itt_plot_estimates_npt.jpg", width = 6, height = 6)
```

\pagebreak  

# Personal PM2.5
```{r}
# Repeat analysis above, but with Personal PM from NPT area only
pm_data_2row <- analysis_data %>% 
  filter(area == "NPT") %>% 
  mutate(outcome = mp_mean_visit) %>%  # select outcome here
  arrange(area, home, adult_id_char, winter_id, sampling_visit) %>% 
  group_by(area, home, adult_id_char, winter_id) %>% 
  mutate(outcome = if_else(winter_id == 1, mean(outcome, na.rm = T), outcome)) %>% 
  dplyr::select(area, home, adult_id_char, winter_id, sampling_visit, 
                cohort, treatment, outcome, income, education, residents_smoke, 
                home_sqm_2level, burn_level, gender, chimney_clean, stove_age, 
                stove_grade, age, bmi, visit_intervention_diff,
                treatment_filter_type, filter_compliance, kw_perc_expected,
                burn_level_3level, chimney_clean_3level, age_2level,
                bmi_2level, income_2level, income_3level, stove_age_2level,
                steps, steps_2level, steps_4level, moisture_ave,
                hypertension, wood_collect_3level) %>% 
  ungroup() %>% 
  distinct(area, home, winter_id, sampling_visit, .keep_all = T) %>% 
  group_by(area, home) %>% 
  pivot_wider(names_from = "winter_id", values_from = "outcome") %>% 
  arrange(area, home, sampling_visit) %>% 
  mutate(outcome = `2`,
         baseline_outcome = `1`,
         baseline_outcome = if_else(is.na(baseline_outcome), first(baseline_outcome),
                                    baseline_outcome)) %>% 
  replace_with_na(replace = list(baseline_outcome = NaN, outcome = NaN)) %>% 
  filter(visit_intervention_diff != 9999) %>% 
  ungroup() 


itt_pm_results_primary <- lmer(log(outcome) ~ treatment + 
                                baseline_outcome + (1 | adult_id_char:home:cohort), 
                                data = pm_data_2row)

#table(model.frame(itt_pm_results_primary)$treatment)

#nobs(itt_pm_results_primary)

#isSingular(itt_pm_results_primary)

#summary(itt_pm_results_primary)

tidy_results_primary <- tidy(itt_pm_results_primary, conf.int = TRUE) %>% 
  mutate(group_filter = if_else(grepl("treatment", term), 1, 0)) %>% 
  filter(group_filter == 1) %>% 
  mutate(term = gsub("treatment", "", term)) %>% 
  mutate(estimate = round((exp(estimate)-1)*100, digits = 2),
         conf.low = round((exp(conf.low)-1)*100, digits = 2),
         conf.high = round((exp(conf.high)-1)*100, digits = 2),
         p.value = round((p.value), digits = 2)) %>% 
  dplyr::select(term, estimate, conf.low, conf.high, p.value) %>% 
  mutate(term = gsub("treatment", "", term),
         model = "Primary") 


itt_pm_results_filter_type <- lmer(log(outcome) ~ treatment_filter_type + 
                                baseline_outcome + (1 | adult_id_char:home:cohort), 
                                data = pm_data_2row)


tidy_results_filter_type <- tidy(itt_pm_results_filter_type, conf.int = TRUE) %>% 
  mutate(group_filter = if_else(grepl("treatment", term), 1, 0)) %>% 
  filter(group_filter == 1) %>% 
  mutate(term = gsub("treatment_filter_type", "", term)) %>% 
  mutate(estimate = round((exp(estimate)-1)*100, digits = 2),
         conf.low = round((exp(conf.low)-1)*100, digits = 2),
         conf.high = round((exp(conf.high)-1)*100, digits = 2),
         p.value = round((p.value), digits = 2)) %>% 
  dplyr::select(term, estimate, conf.low, conf.high, p.value) %>% 
  mutate(model = "Filter Type") 


itt_pm_results_filter_compliance <- lmer(log(outcome) ~ filter_compliance + 
                                baseline_outcome + (1 | adult_id_char:home:cohort), 
                                data = pm_data_2row)


tidy_results_filter_compliance <- tidy(itt_pm_results_filter_compliance, conf.int = TRUE) %>% 
  mutate(group_filter = if_else(grepl("filter_compliance", term), 1, 0)) %>% 
  filter(group_filter == 1) %>% 
  mutate(term = gsub("filter_compliance", "", term)) %>% 
  mutate(estimate = round((exp(estimate)-1)*100, digits = 2),
         conf.low = round((exp(conf.low)-1)*100, digits = 2),
         conf.high = round((exp(conf.high)-1)*100, digits = 2),
         p.value = round((p.value), digits = 2)) %>% 
  dplyr::select(term, estimate, conf.low, conf.high, p.value) %>% 
  mutate(model = "Filter Compliance") 


# Use fitbit steps (quartiles) as a measure of compliance to wearing personal PM monitors
itt_pm_results_fitbit_steps <- lmer(log(outcome) ~ treatment + steps_4level + 
                                baseline_outcome + (1 | adult_id_char:home:cohort), 
                                data = pm_data_2row)


tidy_results_fitbit_steps <- tidy(itt_pm_results_fitbit_steps, conf.int = TRUE) %>% 
  mutate(group_filter = if_else(grepl("treatment", term), 1, 0)) %>% 
  filter(group_filter == 1) %>% 
  mutate(term = gsub("treatment", "", term)) %>% 
  mutate(estimate = round((exp(estimate)-1)*100, digits = 2),
         conf.low = round((exp(conf.low)-1)*100, digits = 2),
         conf.high = round((exp(conf.high)-1)*100, digits = 2),
         p.value = round((p.value), digits = 2)) %>% 
  dplyr::select(term, estimate, conf.low, conf.high, p.value) %>% 
  mutate(model = "Fitbit Steps") 


itt_pm_results_confounders <- lmer(log(outcome) ~ treatment + 
                                education + residents_smoke + home_sqm_2level +
                                burn_level_3level + gender + chimney_clean_3level + 
                                stove_grade + age + bmi + 
                                baseline_outcome + (1 | adult_id_char:home:cohort), 
                                data = pm_data_2row)


tidy_results_confounders <- tidy(itt_pm_results_confounders, conf.int = TRUE) %>% 
  mutate(group_filter = if_else(grepl("treatment", term), 1, 0)) %>% 
  filter(group_filter == 1) %>% 
  mutate(term = gsub("treatment", "", term)) %>% 
  mutate(estimate = round((exp(estimate)-1)*100, digits = 2),
         conf.low = round((exp(conf.low)-1)*100, digits = 2),
         conf.high = round((exp(conf.high)-1)*100, digits = 2),
         p.value = round((p.value), digits = 2)) %>% 
  dplyr::select(term, estimate, conf.low, conf.high, p.value) %>% 
  mutate(term = gsub("treatment", "", term),
         model = "Confounders")


# Calculate ICC
## The ratio of the between-cluster variance to the total variance
## It can also be interpreted as the correlation among observations within the same cluster
icc_model <- lmer(outcome ~ (1 | adult_id_char), pm_data_2row)
pm_icc <- icc(icc_model)


tidy_results_combined <- rbind(tidy_results_primary, tidy_results_filter_type,
                               #tidy_results_filter_compliance, 
                               tidy_results_fitbit_steps,
                               tidy_results_confounders)
kable(tidy_results_primary)


itt_plot_estimates <- tidy_results_combined %>%
  mutate(model = factor(model,
                        levels = c("Primary", "Filter Type", 
                                   #"Filter Compliance", 
                                   "Fitbit Steps",
                                   "Confounders"))) %>% 
  ggplot(aes(group = term, shape = term)) +
    geom_point(aes(x=model, y=estimate), 
               position = position_dodge(width = 0.5), size = 4) +
    geom_errorbar(aes(x=model, ymin=conf.low, ymax=conf.high), 
                  position = position_dodge(width = 0.5), size = 1.2, width = 0.5) +
    geom_hline(yintercept = 0) +
    theme_bw() +  
    ggtitle(label = "PM Model - ITT framework",
            subtitle = "ICC for Participant = 0.41") +
    labs(y = "% difference compared to Placebo") +
    labs(x = "", group = "", shape = "") +
    theme(title = element_text(size = 16), 
          axis.text.x = element_text(size = 16, colour = "black", angle = 45,
                                     hjust = 1, vjust = .8),
          axis.text.y = element_text(size = 16, colour = "black"),
          axis.title.y = element_text(size = 16,
                                      margin = margin(t = 0, r = 20, b = 0, l = 0)),
          axis.line.x = element_line(colour = "black", size = 1.2), 
          axis.line.y = element_line(colour = "black", size = 1.2), 
          axis.ticks = element_blank(), 
          panel.border = element_blank(), 
          panel.grid = element_blank(),
          legend.position = "top",
          legend.text = element_text(size = 14, colour = "black")) 
itt_plot_estimates


plot(itt_pm_results_primary, main = "ITT Primary Model", 
     xlab = "fitted values", ylab = "residuals")
qqnorm(residuals(itt_pm_results_primary), main = "ITT Primary Model")
qqline(residuals(itt_pm_results_primary))
```

\pagebreak  

# Indoor/Area PM2.5 Interaction Analysis
```{r}
# Prep Data
pm_data_2row <- analysis_data %>% 
  mutate(outcome = pm_mean_visit) %>%  # select outcome here
  arrange(area, home, adult_id_char, winter_id, sampling_visit) %>% 
  group_by(area, home, adult_id_char, winter_id) %>% 
  mutate(outcome = if_else(winter_id == 1, mean(outcome, na.rm = T), outcome)) %>% 
  dplyr::select(area, home, adult_id_char, winter_id, sampling_visit, 
                cohort, treatment, outcome, income, education, residents_smoke, 
                home_sqm_2level, burn_level, gender, chimney_clean, stove_age, 
                stove_grade, age, age_2level, bmi, visit_intervention_diff, 
                treatment_filter_type, filter_compliance, kw_perc_expected,
                burn_level_3level, chimney_clean_3level, age_2level,
                bmi_2level, income_2level, income_3level, stove_age_2level,
                hypertension, wood_collect_3level, home_year_built_2level,
                steps, steps_2level, steps_4level,
                home_floors_2level, wood_collect_method) %>% 
  ungroup() %>% 
  distinct(area, home, winter_id, sampling_visit, .keep_all = T) %>% 
  group_by(area, home) %>% 
  pivot_wider(names_from = "winter_id", values_from = "outcome") %>% 
  arrange(area, home, sampling_visit) %>% 
  mutate(outcome = `2`,
         baseline_outcome = `1`,
         baseline_outcome = if_else(is.na(baseline_outcome), first(baseline_outcome),
                                    baseline_outcome)) %>% 
  replace_with_na(replace = list(baseline_outcome = NaN, outcome = NaN)) %>% 
  filter(visit_intervention_diff != 9999) %>% 
  ungroup() 


# Function for area PM interaction analysis
int_function <- function(data, interaction_var, interaction_label) {
  
  new_model_data <- data %>% 
    rename(int_var = interaction_var)
  
  
# Run primary model and print results
itt_results_int <<- lmer(log(outcome) ~ treatment*int_var + 
                                baseline_outcome + (1 | home:cohort:area), 
                                data = new_model_data)

#write_rds(itt_results_int, paste0(file_path, "Output/itt_pm_results_int_age.rds"))


save_summary <<- summary(itt_results_int)

int_emmeans <<- emmeans(itt_results_int, revpairwise ~ treatment | int_var)

#summary(int_emmeans, conf.int = TRUE)

save_contrasts_full <<- summary(int_emmeans)

save_contrasts <<- confint(int_emmeans$contrasts) %>% 
  mutate(estimate = round((exp(estimate)-1)*100, digits = 2),
         conf.low = round((exp(lower.CL)-1)*100, digits = 2),
         conf.high = round((exp(upper.CL)-1)*100, digits = 2)) %>% 
  dplyr::select(contrast, int_var, estimate, conf.low, conf.high)

obs <<- table(model.frame(itt_results_int)$treatment)

n_table <<- table(new_model_data$int_var, new_model_data$treatment)

plot_results <- save_contrasts %>% 
  ggplot(aes(group = contrast, shape = contrast)) +
  geom_point(aes(x=int_var, y=estimate), 
             position = position_dodge(width = 0.5), size = 4) +
  geom_errorbar(aes(x=int_var, ymin=conf.low, ymax=conf.high), 
             position = position_dodge(width = 0.5), size = 1.2, width = 0.5) +
  geom_hline(yintercept = 1) +
  theme_bw() +  
  ggtitle(label = "Interaction contrasts, ITT framework, Area PM",
          subtitle = paste0("Interaction term = ", interaction_label)) +
  labs(y = "% difference") +
  labs(x = "", group = "", shape = "") +
  theme(title = element_text(size = 16), 
          axis.text.x = element_text(size = 16, colour = "black", angle = 45,
                                     hjust = 1, vjust = .8),
          axis.text.y = element_text(size = 16, colour = "black"),
          axis.title.y = element_text(size = 16,
                                      margin = margin(t = 0, r = 20, b = 0, l = 0)),
          axis.line.x = element_line(colour = "black", size = 1.2), 
          axis.line.y = element_line(colour = "black", size = 1.2), 
          axis.ticks = element_blank(), 
          panel.border = element_blank(), 
          panel.grid = element_blank(),
          legend.position = "top",
          legend.text = element_text(size = 14, colour = "black")) 

pm_summary_table <<- new_model_data %>% 
  filter(!is.na(int_var)) %>% 
  group_by(int_var, treatment) %>% 
  summarize("Mean PM" = mean(outcome, na.rm = TRUE),
            "n" = n(),
            "SD PM" = sd(outcome, na.rm = TRUE),
            "Min PM" = min(outcome, na.rm = TRUE),
            "Median PM" = median(outcome, na.rm = TRUE),
            "Max PM" = max(outcome, na.rm = TRUE))


plot_results 

}


# Run interaction function for the following variables:
#int_function(pm_data_2row, "area", "Study area") # need to remove random effect in model
int_function(pm_data_2row, "home_floors_2level", "Floors in home")
int_function(pm_data_2row, "home_sqm_2level", "Home Square Meters")
int_function(pm_data_2row, "education", "Education")
int_function(pm_data_2row, "income_2level", "Income")
int_function(pm_data_2row, "home_year_built_2level", "Year home was built")
int_function(pm_data_2row, "stove_age_2level", "Stove age")
int_function(pm_data_2row, "stove_grade", "Stove grade")
int_function(pm_data_2row, "chimney_clean_3level", "When was chimney cleaned")
int_function(pm_data_2row, "wood_collect_3level", "When was wood collected")
int_function(pm_data_2row, "wood_collect_method", "Wood collect method")
int_function(pm_data_2row, "burn_level_3level", "Burn level")
int_function(pm_data_2row, "residents_smoke", "Residents Smoke")
# Use adult_id_char as distinct filter and random effect in model
int_function(pm_data_2row, "age_2level", "Resident Age")
int_function(pm_data_2row, "gender", "Resident Gender")


# Use the following lines to help fill in information for publication tables:
obs <- pm_data_2row %>% 
  filter(!is.na(outcome)) %>% 
  filter(!is.na(baseline_outcome)) %>%
  filter(!is.na(area)) %>% 
  filter(!is.na(cohort)) %>% 
  filter(!is.na(treatment)) %>% 
  filter(!is.na(gender)) %>%
  group_by(gender, treatment) %>% 
  count()
obs
save_contrasts
Anova(itt_results_int)


n_table
pm_summary_table
save_summary
save_contrasts_full

#((exp(-.418)-1)*100)
```

\pagebreak  

# Personal PM2.5 Interaction Analysis
```{r}
# Prep Data
pm_data_2row <- analysis_data %>% 
  filter(area == "NPT") %>% 
  mutate(outcome = mp_mean_visit) %>%  # select outcome here
  arrange(area, home, adult_id_char, winter_id, sampling_visit) %>% 
  group_by(area, home, adult_id_char, winter_id) %>% 
  mutate(outcome = if_else(winter_id == 1, mean(outcome, na.rm = T), outcome)) %>% 
  dplyr::select(area, home, adult_id_char, winter_id, sampling_visit, 
                cohort, treatment, outcome, income, education, residents_smoke, 
                home_sqm_2level, burn_level, gender, chimney_clean, stove_age, 
                stove_grade, age, bmi, visit_intervention_diff, 
                treatment_filter_type, filter_compliance, kw_perc_expected,
                burn_level_3level, chimney_clean_3level, age_2level,
                bmi_2level, income_2level, income_3level, stove_age_2level,
                hypertension, wood_collect_3level, home_year_built_2level,
                steps, steps_2level, steps_4level,
                home_floors_2level, wood_collect_method) %>% 
  ungroup() %>% 
  distinct(area, adult_id_char, home, winter_id, sampling_visit, .keep_all = T) %>% 
  group_by(area, adult_id_char) %>% 
  pivot_wider(names_from = "winter_id", values_from = "outcome") %>% 
  arrange(area, adult_id_char, home, sampling_visit) %>% 
  mutate(outcome = `2`,
         baseline_outcome = `1`,
         baseline_outcome = if_else(is.na(baseline_outcome), first(baseline_outcome),
                                    baseline_outcome)) %>% 
  replace_with_na(replace = list(baseline_outcome = NaN, outcome = NaN)) %>% 
  filter(visit_intervention_diff != 9999) %>% 
  ungroup() 



int_function <- function(data, interaction_var, interaction_label) {
  
  new_model_data <- data %>% 
    rename(int_var = interaction_var)
  
  
# Run primary model and print results
itt_results_int <<- lmer(log(outcome) ~ treatment*int_var + 
                                baseline_outcome + (1 | adult_id_char:home:cohort), 
                                data = new_model_data)

#write_rds(itt_results_int, paste0(file_path, "Output/itt_pm_results_int_age.rds"))


save_summary <<- summary(itt_results_int)

int_emmeans <<- emmeans(itt_results_int, revpairwise ~ treatment | int_var)

#summary(int_emmeans, conf.int = TRUE)

save_contrasts_full <<- summary(int_emmeans)

save_contrasts <<- confint(int_emmeans$contrasts) %>% 
  mutate(estimate = round((exp(estimate)-1)*100, digits = 2),
         conf.low = round((exp(lower.CL)-1)*100, digits = 2),
         conf.high = round((exp(upper.CL)-1)*100, digits = 2)) %>% 
  dplyr::select(contrast, int_var, estimate, conf.low, conf.high)

obs <<- table(model.frame(itt_results_int)$treatment)

n_table <<- table(new_model_data$int_var, new_model_data$treatment)

plot_results <- save_contrasts %>% 
  ggplot(aes(group = contrast, shape = contrast)) +
  geom_point(aes(x=int_var, y=estimate), 
             position = position_dodge(width = 0.5), size = 4) +
  geom_errorbar(aes(x=int_var, ymin=conf.low, ymax=conf.high), 
             position = position_dodge(width = 0.5), size = 1.2, width = 0.5) +
  geom_hline(yintercept = 1) +
  theme_bw() +  
  ggtitle(label = "Interaction contrasts, ITT framework, Personal PM",
          subtitle = paste0("Interaction term = ", interaction_label)) +
  labs(y = "% difference") +
  labs(x = "", group = "", shape = "") +
  theme(title = element_text(size = 16), 
          axis.text.x = element_text(size = 16, colour = "black", angle = 45,
                                     hjust = 1, vjust = .8),
          axis.text.y = element_text(size = 16, colour = "black"),
          axis.title.y = element_text(size = 16,
                                      margin = margin(t = 0, r = 20, b = 0, l = 0)),
          axis.line.x = element_line(colour = "black", size = 1.2), 
          axis.line.y = element_line(colour = "black", size = 1.2), 
          axis.ticks = element_blank(), 
          panel.border = element_blank(), 
          panel.grid = element_blank(),
          legend.position = "top",
          legend.text = element_text(size = 14, colour = "black")) 

pm_summary_table <<- new_model_data %>% 
  filter(!is.na(int_var)) %>% 
  group_by(int_var, treatment) %>% 
  summarize("Mean PM" = mean(outcome, na.rm = TRUE),
            "n" = n(),
            "SD PM" = sd(outcome, na.rm = TRUE),
            "Min PM" = min(outcome, na.rm = TRUE),
            "Median PM" = median(outcome, na.rm = TRUE),
            "Max PM" = max(outcome, na.rm = TRUE))


plot_results 

}


int_function(pm_data_2row, "home_floors_2level", "Floors in home")
int_function(pm_data_2row, "home_sqm_2level", "Home Square Meters")
int_function(pm_data_2row, "education", "Education")
int_function(pm_data_2row, "income_2level", "Income")
int_function(pm_data_2row, "home_year_built_2level", "Year home was built")
int_function(pm_data_2row, "stove_age_2level", "Stove age")
int_function(pm_data_2row, "stove_grade", "Stove grade")
int_function(pm_data_2row, "chimney_clean_3level", "When was chimney cleaned")
int_function(pm_data_2row, "wood_collect_3level", "When was wood collected")
int_function(pm_data_2row, "wood_collect_method", "Wood collect method")
int_function(pm_data_2row, "burn_level_3level", "Burn level")
int_function(pm_data_2row, "residents_smoke", "Residents Smoke")
int_function(pm_data_2row, "steps_2level", "Fitbit Steps - 2 Level")
int_function(pm_data_2row, "steps_4level", "Fitbit Steps - 4 Level")
int_function(pm_data_2row, "age_2level", "Resident Age")
int_function(pm_data_2row, "gender", "Resident Gender")


obs <- pm_data_2row %>% 
  filter(!is.na(outcome)) %>% 
  filter(!is.na(baseline_outcome)) %>%
  filter(!is.na(area)) %>% 
  filter(!is.na(cohort)) %>% 
  filter(!is.na(treatment)) %>% 
  filter(!is.na(age_2level)) %>%
  group_by(age_2level, treatment) %>% 
  count()
obs
save_contrasts
Anova(itt_results_int)


n_table
pm_summary_table
save_summary
save_contrasts_full


#((exp(-.418)-1)*100)
```


# Boxplot figure for publication
```{r}
cbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", 
               "#0072B2", "#D55E00", "#CC79A7")

indoor_pm_n <- analysis_data %>% 
  filter(!is.na(pm_mean_visit)) %>% 
  filter(!is.na(treatment)) %>% 
  group_by(winter_id, treatment) %>% 
  count()
indoor_pm_n


indoor_pm_boxplot <- analysis_data %>% 
  filter(!is.na(pm_mean_visit)) %>% 
  filter(!is.na(treatment)) %>% 
  mutate("Winter Sampling Period:" = factor(winter_id, levels = c(1, 2),
                                  labels = c("Baseline", "Post-Intervention"))) %>% 
  ggplot() + 
    geom_boxplot(aes(treatment, pm_mean_visit, fill = `Winter Sampling Period:`, size = 1), 
                 lwd = 1.2, colour = "black", 
                 fatten = 1, outlier.size = 1.5, width = 0.35) +
    labs(y = expression(paste("48-hour Mean Indoor PM"[2.5], " (", mu, g/m^3, ")"))) +
    theme_minimal() +
    scale_y_log10() +
    theme(plot.title = element_text(size = 18, colour = "black"),
          strip.text = element_text(size = 16, colour = "black"),
          axis.text.x = element_text(size = 16, colour = "black", 
                                     vjust = 0.5),
          axis.text.y = element_text(size = 16, colour = "black"),
          axis.title.y = element_text(size = 16, colour = "black"),
          axis.title.x = element_blank(),
          axis.line.x = element_line(colour = "black", size = 1.2), 
          axis.line.y = element_line(colour = "black", size = 1.2), 
          legend.title = element_text(size = 16, colour = "black"),
          legend.text = element_text(size = 16, colour = "black"),
          legend.position = "top",
          panel.grid.major.x = element_blank(),
          axis.ticks = element_blank()) +
    scale_fill_manual(values = c("#E69F00", "#56B4E9"))
indoor_pm_boxplot


#ggsave("elders_pm_boxplots.jpg", width = 8, height = 5)
```

# Boxplot figure for results letter
```{r}
cbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", 
               "#0072B2", "#D55E00", "#CC79A7")

indoor_pm_boxplot <- analysis_data %>% 
  filter(area == "NPT") %>% 
  mutate("Winter:" = factor(winter_id, levels = c(1, 2),
                                  labels = c("1st Winter/Pre-Intervention", "2nd Winter/Post-Intervention")),
         treatment = factor(treatment, 
                            levels = c("Placebo", "Education", "Filter"),
                            labels = c("Placebo Group", "Education Group", "Filter Group"))) %>% 
  filter(!is.na(pm_mean_visit)) %>% 
  filter(pm_mean_visit < 200) %>% 
  filter(!is.na(treatment)) %>% 
  ggplot(aes(treatment, pm_mean_visit, fill = `Winter:`)) + 
    geom_boxplot(aes(treatment, pm_mean_visit, fill = `Winter:`, size = 1), 
                 lwd = 1.2, colour = "black", 
                 fatten = 1, outlier.size = 1.5, width = 0.35,
                 outlier.shape = NA) +
    #stat_summary(fun.y=mean, geom="point", shape = 3, size = 3, stroke = 2, 
     #          position=position_dodge(0.35)) +
    labs(y = expression(paste("Indoor PM"[2.5], " (", mu, g/m^3, ")")),
         fill = "") +
    theme_minimal() +
    scale_y_continuous(breaks = seq(0, 130, by = 10), labels = seq(0, 130, by = 10), limits = c(0, 130)) +
    #scale_y_log10() +
    theme(plot.title = element_text(size = 18, colour = "black"),
          strip.text = element_text(size = 16, colour = "black"),
          axis.text.x = element_text(size = 16, colour = "black", 
                                     vjust = 0.5),
          axis.text.y = element_text(size = 16, colour = "black"),
          axis.title.y = element_text(size = 16, colour = "black"),
          axis.title.x = element_blank(),
          axis.line.x = element_line(colour = "black", size = 1.2), 
          axis.line.y = element_line(colour = "black", size = 1.2), 
          legend.title = element_text(size = 16, colour = "black"),
          legend.text = element_text(size = 16, colour = "black"),
          legend.position = "top",
          panel.grid.major.x = element_blank(),
          axis.ticks = element_blank()) +
    scale_fill_manual(values = c("#E69F00", "#56B4E9"))
indoor_pm_boxplot



indoor_pm_plot <- analysis_data %>% 
  filter(area == "NPT") %>% 
  filter(pm_mean_visit < 200) %>% 
  mutate("Winter:" = factor(winter_id, levels = c(1, 2),
                                  labels = c("1st Winter/Pre-Intervention", "2nd Winter/Post-Intervention")),
         treatment = factor(treatment, 
                            levels = c("Placebo", "Education", "Filter"),
                            labels = c("Placebo Group", "Education Group", "Filter Group"))) %>% 
  filter(!is.na(pm_mean_winter)) %>% 
  filter(!is.na(treatment)) %>% 
  distinct(home, winter_id, .keep_all = T) %>% 
  ggplot() + 
    #geom_hline(yintercept = 35, color = "red", linetype = 2) + 
    geom_point(aes(treatment, pm_mean_winter, fill = `Winter:`), 
               shape = 21, size = 3, position=position_jitterdodge(seed = 1)) +
    labs(y = "Indoor PM2.5", fill = "", color = "") +
    theme_minimal() +
    theme(plot.title = element_text(size = 18, colour = "black"),
          strip.text = element_text(size = 16, colour = "black"),
          axis.text.x = element_text(size = 16, colour = "black", 
                                     vjust = 0.5),
          axis.text.y = element_text(size = 16, colour = "black"),
          axis.title.y = element_text(size = 16, colour = "black"),
          axis.title.x = element_blank(),
          axis.line.x = element_line(colour = "black", size = 1.2), 
          axis.line.y = element_line(colour = "black", size = 1.2), 
          legend.title = element_text(size = 16, colour = "black"),
          legend.text = element_text(size = 16, colour = "black"),
          legend.position = "top",
          panel.grid.major.x = element_blank(),
          axis.ticks = element_blank()) +
    scale_fill_manual(values = c("#E69F00", "#56B4E9")) +
    scale_color_manual(values = c("#E69F00", "#56B4E9")) 
indoor_pm_plot


#ggsave("elders_pm_dotplots.jpg", width = 8, height = 5)
```

