---
title: 'EldersAIR: Main analysis - Spirometry Outcomes'
author: "Ethan Walker"
date: "Started 6 May 2021; Updated 6 May 2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, eval = TRUE, include = TRUE,
                      message = FALSE, warning = FALSE)
```

```{r}
library(readxl)
library(naniar)
library(lubridate)
library(emmeans)
library(broom)
library(broom.mixed)
library(zoo)
library(car)
library(lme4)
library(lmerTest)
library(mctest)
library(tidyverse)
library(knitr)
library(kableExtra)
#library(MASS)
library(faraway)
library(splines)
library(influence.ME)
library(sjstats)
```

```{r}
# Load data

file_path <- c("C:/Users/ethan.walker/Box/Ethan Walker UM/R/EldersAIR/")

analysis_data <- read_rds(paste0(file_path, "Output/elders_cleaned_dataset_by_visit.rds")) 
```


```{r}
itt_health_function <- function(data, outcome_var, outcome_label) {

analysis_data_2row <- data %>% 
  filter(spiro_status == "Acceptable") %>% 
  rename(outcome = outcome_var) %>%  
  arrange(area, home, adult_id_char, winter_id, sampling_visit) %>% 
  group_by(area, home, adult_id_char, winter_id) %>% 
  mutate(outcome = if_else(winter_id == 1, mean(outcome, na.rm = T), outcome)) %>% 
  dplyr::select(area, home, adult_id_char, winter_id, sampling_visit, 
                cohort, treatment, outcome, income, education, residents_smoke, 
                home_sqm_2level, burn_level, gender, chimney_clean, stove_age, 
                stove_grade, age, bmi, visit_intervention_diff,
                treatment_filter_type, filter_compliance, kw_perc_expected) %>% 
  ungroup() %>% 
  distinct(area, adult_id_char, winter_id, sampling_visit, .keep_all = T) %>% 
  group_by(area, adult_id_char) %>% 
  pivot_wider(names_from = "winter_id", values_from = "outcome") %>% 
  arrange(area, home, adult_id_char, sampling_visit) %>% 
  mutate(outcome = `2`,
         baseline_outcome = `1`,
         baseline_outcome = if_else(is.na(baseline_outcome), first(baseline_outcome),
                                    baseline_outcome)) %>% 
  replace_with_na(replace = list(baseline_outcome = NaN, outcome = NaN)) %>% 
  filter(visit_intervention_diff != 9999) %>% 
  ungroup()



itt_health_results_primary <<- lmer(outcome ~ treatment +
                                baseline_outcome + (1 | adult_id_char:home:cohort:area), 
                                data = analysis_data_2row)


model_singular <<- isSingular(itt_health_results_primary)

model_summary <<- summary(itt_health_results_primary)

tidy_results_primary <<- tidy(itt_health_results_primary, conf.int = TRUE) %>% 
  mutate(group_filter = if_else(grepl("treatment", term), 1, 0)) %>% 
  filter(group_filter == 1) %>% 
  mutate(term = gsub("treatment", "", term)) %>% 
  mutate(estimate = round((estimate), digits = 2),
         conf.low = round((conf.low), digits = 2),
         conf.high = round((conf.high), digits = 2),
         p.value = round((p.value), digits = 2)) %>% 
  dplyr::select(term, estimate, conf.low, conf.high, p.value) %>% 
  mutate(term = gsub("treatment", "", term),
         model = "Primary") 


itt_health_results_confounders <- lmer(outcome ~ treatment + 
                                education + residents_smoke + home_sqm_2level +
                                burn_level + gender + chimney_clean + 
                                stove_grade + age + bmi + 
                                baseline_outcome + (1 | adult_id_char:home:cohort:area), 
                                data = analysis_data_2row)


tidy_results_confounders <<- tidy(itt_health_results_confounders, conf.int = TRUE) %>% 
  mutate(group_filter = if_else(grepl("treatment", term), 1, 0)) %>% 
  filter(group_filter == 1) %>% 
  mutate(term = gsub("treatment", "", term)) %>% 
  mutate(estimate = round((estimate), digits = 2),
         conf.low = round((conf.low), digits = 2),
         conf.high = round((conf.high), digits = 2),
         p.value = round((p.value), digits = 2)) %>% 
  dplyr::select(term, estimate, conf.low, conf.high, p.value) %>% 
  mutate(term = gsub("treatment", "", term),
         model = "Confounders") 


tidy_results_combined <- rbind(tidy_results_primary, tidy_results_confounders)


# Calculate ICC
## The ratio of the between-cluster variance to the total variance
## It can also be interpreted as the correlation among observations within the same cluster
icc_model <- lmer(outcome ~ (1 | adult_id_char), analysis_data_2row)
model_icc <<- icc(icc_model)


itt_plot_estimates <- tidy_results_combined %>%
  mutate(model = factor(model,
                        levels = c("Primary", "Confounders"))) %>% 
  ggplot(aes(group = term, shape = term)) +
    geom_point(aes(x=model, y=estimate), 
               position = position_dodge(width = 0.5), size = 4) +
    geom_errorbar(aes(x=model, ymin=conf.low, ymax=conf.high), 
                  position = position_dodge(width = 0.5), size = 1.2, width = 0.5) +
    geom_hline(yintercept = 0) +
    theme_bw() +  
    ggtitle(label = paste0(outcome_label, " - ITT framework")) +
    labs(y = "Estimate compared to Placebo") +
    labs(x = "", group = "", shape = "") +
    theme(title = element_text(size = 16), 
          axis.text.x = element_text(size = 16, colour = "black", angle = 45,
                                     hjust = 1, vjust = .8),
          axis.text.y = element_text(size = 16, colour = "black"),
          axis.title.y = element_text(size = 16,
                                      margin = margin(t = 0, r = 20, b = 0, l = 0)),
          axis.line.x = element_line(colour = "black", size = 1.2), 
          axis.line.y = element_line(colour = "black", size = 1.2), 
          axis.ticks = element_blank(), 
          panel.border = element_blank(), 
          panel.grid = element_blank(),
          legend.position = "top",
          legend.text = element_text(size = 14, colour = "black")) 
itt_plot_estimates

}
```

# FVC ITT Results
```{r}
itt_health_function(analysis_data, "fvc", "FVC")
kable(tidy_results_primary)
plot(itt_health_results_primary, main = "ITT Primary Model", 
     xlab = "fitted values", ylab = "residuals")
qqnorm(residuals(itt_health_results_primary), main = "ITT Primary Model")
qqline(residuals(itt_health_results_primary))
```

\pagebreak  

# FEV1 ITT Results
```{r}
itt_health_function(analysis_data, "fev1", "FEV1")
kable(tidy_results_primary)
plot(itt_health_results_primary, main = "ITT Primary Model", 
     xlab = "fitted values", ylab = "residuals")
qqnorm(residuals(itt_health_results_primary), main = "ITT Primary Model")
qqline(residuals(itt_health_results_primary))
```
