---
title: 'EldersAIR: manuscript tables/figures'
author: "Ethan Walker"
date: "Started 1 March 2021, Updated 3 March 2021"
output:
  powerpoint_presentation: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, eval = TRUE, 
                      include = TRUE, warning = FALSE,
                      fig.height = 6, fig.width = 8)
```

```{r, message=FALSE}
library(tidyverse)
library(readxl)
library(naniar)
library(lubridate)
library(zoo)
library(knitr)
jv_palette <- c("#330099","#CC0066","#FF6633", 
                 "#0099CC", "#FF9900","#CC6633",
                  "#FF3366", "#33CC99", "#33999")
cbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", 
               "#0072B2", "#D55E00", "#CC79A7")
```


```{r}
# Load individual datasets

file_path <- c("C:/Users/ethan.walker/Box/Ethan Walker UM/R/EldersAIR/")

elders_ids_linked <- read_rds(paste0(file_path, "Output/elders_ids_linked.rds"))

elders_demographics <- read_rds(paste0(file_path, "Output/elders_demographics.rds"))

elders_demographics_full <- read_rds(paste0(file_path, "Output/elders_demographics_full.rds"))

elders_medvisit_clean <- read_rds(paste0(file_path, "Output/elders_medvisit_clean.rds"))

elders_pm <- read_rds(paste0(file_path, "Output/elders_pm_clean.rds")) 
```


# Number of homes in Figure 1
```{r}
# Step 1: Winter 1 homes
demographics_check <- elders_demographics %>% 
  filter(winter_id == 1) %>% 
  distinct(area, home, .keep_all = T) %>% 
  count(area)

demographics_check


# Step 2: Randomized homes
demographics_check <- elders_demographics_full %>% 
  arrange(area, home, winter_id) %>% 
  mutate(filter_var = if_else(home == "NPE5197" | home == "NPE5198" | home == "NPE5199" |
                              home == "FDE314" | home == "FDE316" | home == "FDE318" |
                              home == "FDE413" | home == "FDE412B" | home == "NPE5314" |
                              home == "NPE5317", 1, 0)) %>% 
  filter(filter_var == 0 | is.na(filter_var)) %>% 
  filter(!is.na(home)) %>% 
  filter(!is.na(treatment)) %>% 
  filter(winter_id == 2) %>% 
  distinct(area, home, .keep_all = T) %>% 
  count(treatment, area)

demographics_check


# Step 3: Winter 2 homes
demographics_check <- elders_demographics %>% 
  filter(winter_id == 2) %>% 
  distinct(area, home, .keep_all = T) %>% 
  count(treatment, area)

demographics_check
```


# Number of participants in Figure 1
```{r}
# Step 1: Winter 1 participants
demographics_check <- elders_demographics %>% 
  filter(winter_id == 1) %>% 
  distinct(area, adult_id_char, .keep_all = T) %>% 
  count(area)

demographics_check


# Step 2: Randomized participants
demographics_check <- elders_demographics_full %>% 
  arrange(area, home, winter_id) %>% 
  mutate(filter_var = if_else(home == "NPE5197" | home == "NPE5198" | home == "NPE5199" |
                              home == "FDE314" | home == "FDE316" | home == "FDE318" |
                              home == "FDE413" | home == "FDE412B" | home == "NPE5314" |
                              home == "NPE5317", 1, 0)) %>% 
  filter(filter_var == 0 | is.na(filter_var)) %>% 
  filter(!is.na(home)) %>% 
  filter(!is.na(treatment)) %>% 
  filter(winter_id == 2) %>% 
  distinct(area, adult_id_char, .keep_all = T) %>% 
  count(treatment, area)

demographics_check


# Step 3: Winter 2 participants
demographics_check <- elders_demographics %>% 
  filter(winter_id == 2) %>% 
  distinct(area, adult_id_char, .keep_all = T) %>% 
  count(treatment, area)

demographics_check
```


# Number of med visits in Figure 1
```{r}
# Step 1: Winter 1 visits
medvisit_check <- elders_medvisit_clean %>% 
  filter(winter_id == 1 & !is.na(sampling_visit)) %>% 
  filter_at(vars(sp02:spiro_result), any_vars(!is.na(.))) %>% 
  count(area)

medvisit_check


# Step 2: Winter 2 visits
medvisit_check <- elders_medvisit_clean %>% 
  filter(!is.na(treatment)) %>% 
  filter(winter_id == 2 & !is.na(sampling_visit)) %>% 
  filter_at(vars(sp02:spiro_result), any_vars(!is.na(.))) %>% 
  count(treatment, area)

medvisit_check
```


# Number of exposure samples in Figure 1
```{r}
# Step 1: Winter 1 samples
exposure_check <- elders_pm %>% 
  arrange(area, home, winter_id, sampling_visit) %>% 
  distinct(area, home, winter_id, sampling_visit, .keep_all = T) %>% 
  filter(winter_id == 1) %>% 
  count(area)

exposure_check


# Step 2: Winter 2 samples
exposure_check <- elders_pm %>% 
  filter(!is.na(treatment)) %>% 
  arrange(area, home, winter_id, sampling_visit) %>% 
  distinct(area, home, winter_id, sampling_visit, .keep_all = T) %>% 
  filter(winter_id == 2) %>% 
  count(treatment, area)

exposure_check
```

