---
title: "EldersAIR initial PM data work"
author: "Ethan Walker"
date: "Started 20 Feb 2020, Updated 24 Feb 2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE}
library(tidyverse)
library(readxl)
library(naniar)
library(lubridate)
library(zoo)
library(knitr)
jv_palette <- c("#330099","#CC0066","#FF6633", 
                 "#0099CC", "#FF9900","#CC6633",
                  "#FF3366", "#33CC99", "#33999")

elders_ids_linked <- read_rds("Output/elders_ids_linked.rds") %>% 
  filter(winter_id == 1 | winter_id == 2) %>% 
  arrange(area, adult_id_num)
```

# Initial load, format, save medical visit data
```{r}
## Box location: Update Box location once final data loaded
np_medvisit_initial <- read_xlsx("Input/NP/np_medicalvisit_20200220.xlsx")

np_medvisit_new <- np_medvisit_initial %>% 
  mutate(home_winter_id = HomeWinterID,
         adult_id_num = AdultID,
         sp02 = as.numeric(Sp02),
         pr = as.numeric(PR),
         bp_sys = as.numeric(BPS),
         bp_dia = as.numeric(BPD),
         hr = as.numeric(HR),
         age = as.numeric(Age),
         gender = as.character(Gender),
         height_inches = as.numeric(Height),
         weight_lbs = as.numeric(Weight),
         fvc = as.numeric(PreFVC),
         fev1 = as.numeric(PreFEV),
         fev1_fvc_ratio = as.numeric(fev1/fvc),
         fvc_pp = as.numeric(PredPreFVC),
         fev1_pp = as.numeric(PredPreFEV),
         fev1_fvc_ratio_pp = as.numeric(fev1_pp/fvc_pp),
         spiro_grade = as.character(PreGrade),
         spiro_maneuvers = as.numeric(PreManeuvers),
         spiro_status = as.character(DrStatus),
         spiro_result = as.character(DrResult),
         sampling_visit = as.factor(SamplingVisit),
         area = "NP") %>% 
  select(home_winter_id:area) %>% 
  arrange(home_winter_id) 
  
  
# fix values after check spiro files
np_medvisit_new2 <- np_medvisit_new %>% 
  mutate(sp02 = if_else(sp02 < 80, -999, sp02)) %>% 
  mutate(sp02 = if_else(adult_id_num == 58 & sp02 == 80, -999, sp02)) %>% 
  mutate(pr = if_else(adult_id_num == 58 & pr == 80, -999, pr)) %>%
  mutate(bp_sys = if_else(adult_id_num == 58 & bp_sys == 80, -999, bp_sys)) %>%
  replace_with_na_all(condition = ~.x %in% c(-999, 0)) %>% 
  mutate(fvc = if_else(adult_id_num == "47" & fvc == "1.01", 1.81, fvc),
         fev1 = if_else(adult_id_num == "55" & fev1 == "2.98", 1.98, fev1),
         fvc = if_else(adult_id_num == "104" & fvc == "1.2", 1.65, fvc),
         fev1 = if_else(adult_id_num == "104" & fev1 == "1.2", 1.6, fev1),
         fvc_pp = if_else(adult_id_num == "104" & fvc_pp == "42", 58, fvc_pp),
         fev1_pp = if_else(adult_id_num == "104" & fev1_pp == "56", 75, fev1_pp),
         fev1_fvc_ratio = as.numeric(fev1/fvc),
         fev1_fvc_ratio_pp = as.numeric(fev1_pp/fvc_pp))


## Box location: Update Box location once final data loaded
nn_medvisit_initial <- read_xlsx("Input/NN/nn_medicalvisit_20200220.xlsx")

nn_medvisit_new <- nn_medvisit_initial %>% 
  mutate(home_winter_id = HomeWinterID,
         adult_id_num = AdultID,
         sp02 = as.numeric(Sp02),
         pr = as.numeric(PR),
         bp_sys = as.numeric(BPS),
         bp_dia = as.numeric(BPD),
         hr = as.numeric(HR),
         age = as.numeric(Age),
         gender = as.character(Gender),
         height_inches = as.numeric(Height),
         weight_lbs = as.numeric(Weight),
         fvc = as.numeric(PreFVC),
         fev1 = as.numeric(PreFEV),
         fev1_fvc_ratio = as.numeric(fev1/fvc),
         fvc_pp = as.numeric(PredPreFVC),
         fev1_pp = as.numeric(PredPreFEV),
         fev1_fvc_ratio_pp = as.numeric(fev1_pp/fvc_pp),
         spiro_grade = as.character(PreGrade),
         spiro_maneuvers = as.numeric(PreManeuvers),
         spiro_status = as.character(DrStatus),
         spiro_result = as.character(DrResult),
         sampling_visit = as.factor(SamplingVisit),
         area = "NN") %>% 
  select(home_winter_id:area) %>% 
  arrange(home_winter_id) 

# fix values after check spiro files
nn_medvisit_new2 <- nn_medvisit_new %>% 
  mutate(bp_dia = if_else(bp_dia < 50, -999, bp_dia)) %>% 
  mutate(sp02 = if_else(sp02 < 80, -999, sp02)) %>% 
  mutate(hr = if_else(hr < 40, -999, hr)) %>% 
  mutate(fev1_fvc_ratio = if_else(fvc == -999, -999, fev1_fvc_ratio)) %>% 
  mutate(fev1_fvc_ratio_pp = if_else(fvc == -999, -999, fev1_fvc_ratio_pp)) %>% 
  replace_with_na_all(condition = ~.x %in% c(-999, 0)) %>% 
  replace_with_na(replace = list(bp_sys = c(9, 80))) %>% 
  mutate(age = if_else(adult_id_num == "47" & age == 17, 71, age)) %>% 
  mutate(fvc = if_else(adult_id_num == "87" & fvc == 2.65, 3.14, fvc),
         fev1 = if_else(adult_id_num == "87" & fev1 == 3.4, 2.65, fev1),
         fvc = if_else(adult_id_num == "77" & fvc == 2.19, 2.95, fvc),
         fev1 = if_else(adult_id_num == "77" & fev1 == 2.72, 2.22, fev1),
         fvc = if_else(adult_id_num == "77" & fvc == 0.81, 2.98, fvc),
         fev1 = if_else(adult_id_num == "77" & fev1 == 0.81, 2.38, fev1),
         fvc_pp = if_else(adult_id_num == "77" & fvc_pp == 57, 76, fvc_pp),
         fev1_pp = if_else(adult_id_num == "77" & fev1_pp == 49, 73, fev1_pp),
         fvc = if_else(adult_id_num == "55" & fvc == 1.13, 1.7, fvc),
         fev1 = if_else(adult_id_num == "55" & fev1 == 1.12, 1.18, fev1),
         fvc_pp = if_else(adult_id_num == "55" & fvc_pp == 0.35, 82, fvc_pp),
         fev1_pp = if_else(adult_id_num == "55" & fev1_pp == 2.31, 77, fev1_pp),
         fvc_pp = if_else(adult_id_num == "77" & fvc_pp == 21, 77, fvc_pp),
         fev1_pp = if_else(adult_id_num == "77" & fev1_pp == 27, 79, fev1_pp),
         fvc = if_else(adult_id_num == "79" & fvc == 1.59, 1.66, fvc),
         fev1 = if_else(adult_id_num == "79" & fev1 == 1.59, 1.19, fev1),
         fvc_pp = if_else(adult_id_num == "79" & fvc_pp == 89, 93, fvc_pp),
         fev1_pp = if_else(adult_id_num == "79" & fev1_pp == 123, 91, fev1_pp),
         fvc = if_else(adult_id_num == "61" & fvc == 3.07, 3.43, fvc),
         fvc_pp = if_else(fvc_pp < 1, fvc_pp*1000, fvc_pp),
         fev1_pp = if_else(fev1_pp < 1, fev1_pp*1000, fev1_pp),
         fvc_pp = if_else(fvc_pp < 10, (fvc/fvc_pp)*100, fvc_pp),
         fev1_pp = if_else(fev1_pp < 10, (fev1/fev1_pp)*100, fev1_pp),
         weight_lbs = if_else(adult_id_num == "61" & weight_lbs == 3.43, 127, weight_lbs),
         height_inches = if_else(height_inches == 5, 60, height_inches),
         bp_sys = if_else(adult_id_num == "9" & bp_sys == 94, 104, bp_sys),
         bp_dia = if_else(adult_id_num == "9" & bp_dia == 104, 94, bp_dia),
         fev1_fvc_ratio = as.numeric(fev1/fvc),
         fev1_fvc_ratio_pp = as.numeric(fev1_pp/fvc_pp))

# Check: 
  #% predicted values are a mess


elders_medvisit <- rbind(np_medvisit_new2, nn_medvisit_new2) %>% 
  mutate(bmi = (weight_lbs/(height_inches^2)*703),
         home_winter_id = as.factor(home_winter_id),
         adult_id_num = as.factor(adult_id_num)) %>% 
  left_join(elders_ids_linked, by = c("area", "home_winter_id", "adult_id_num"))

#write_rds(elders_medvisit, "Output/elders_medvisit_clean.rds")
```


# Summary stats to help with further data cleaning
```{r}
elders_medvisit <- read_rds("Output/elders_medvisit_clean.rds") 

medvisit_summary_function <- function(data, var) {
  
  medvisit_summary <- data %>% 
    filter(winter_id == 1) %>% 
    filter(spiro_status == "Acceptable") %>% 
    select(area, var) %>% 
    group_by(area) %>% 
    summarize_all(list(mean=mean, sd=sd, min=min, med=median, max=max), na.rm = TRUE)
  medvisit_summary
  
}

medvisit_summary_function(elders_medvisit, "sp02")
medvisit_summary_function(elders_medvisit, "pr")
medvisit_summary_function(elders_medvisit, "bp_sys")
medvisit_summary_function(elders_medvisit, "bp_dia")
medvisit_summary_function(elders_medvisit, "hr")
medvisit_summary_function(elders_medvisit, "age")
medvisit_summary_function(elders_medvisit, "height_inches")
medvisit_summary_function(elders_medvisit, "weight_lbs")
medvisit_summary_function(elders_medvisit, "bmi")
medvisit_summary_function(elders_medvisit, "fvc")
medvisit_summary_function(elders_medvisit, "fev1")
medvisit_summary_function(elders_medvisit, "fev1_fvc_ratio")
medvisit_summary_function(elders_medvisit, "fvc_pp")
medvisit_summary_function(elders_medvisit, "fev1_pp")
medvisit_summary_function(elders_medvisit, "fev1_fvc_ratio_pp")


summary_stats <- elders_medvisit %>% 
  filter(winter_id == 1) %>% 
  #filter(spiro_status == "Acceptable") %>% 
  filter(!is.na(bp_sys)) %>% 
  group_by(area) %>% 
  distinct(home) %>% 
  summarize(n())
summary_stats
```

