---
title: "EldersAIR Med Visit Summary"
author: "Ethan Walker"
date: "Started 11 March 2020, Updated 12 March 2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

```{r, message=FALSE}
library(tidyverse)
library(readxl)
library(naniar)
library(lubridate)
library(zoo)
library(knitr)
jv_palette <- c("#330099","#CC0066","#FF6633", 
                 "#0099CC", "#FF9900","#CC6633",
                  "#FF3366", "#33CC99", "#33999")
cbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", 
               "#0072B2", "#D55E00", "#CC79A7")
```


```{r}
file_path <- c("C:/Users/ethan.walker/Box/Ethan Walker UM/R/EldersAIR/")

# Load data

elders_ids_linked <- read_rds(paste0(file_path, "Output/elders_ids_linked.rds")) %>% 
  filter(winter_id == 1 | winter_id == 2) %>% 
  arrange(area, adult_id_num)

elders_medvisit <- read_rds(paste0(file_path, "Output/elders_medvisit_clean.rds")) 
```

# Cardiovascular outcomes from Med visit
```{r}
medvisit_plot <- elders_medvisit %>% 
  filter(winter_id == 1) %>% 
  select(area, sp02, pr, bp_sys, bp_dia, hr, age, height_inches,
         weight_lbs, bmi) %>% 
  pivot_longer(cols = c("sp02":"bmi"), names_to = "var") %>% 
  filter(!is.na(value)) %>% 
  ggplot(aes(area, value)) +
    geom_boxplot(aes(size = 1), lwd = 1.2, colour = "black", 
               fatten = 1, outlier.size = 1.5, width = 0.35) +theme_minimal() +
    theme(strip.text = element_text(size = 16, colour = "black"),
          axis.text.x = element_text(size = 16, colour = "black"),
          axis.text.y = element_text(size = 16, colour = "black"),
          axis.title.y = element_text(size = 16, colour = "black"),
          axis.title.x = element_blank(),
          axis.line.x = element_line(colour = "black", size = 1.2), 
          axis.line.y = element_line(colour = "black", size = 1.2), 
          axis.ticks = element_blank()) +
    facet_wrap(~var, scales = "free_y")
medvisit_plot
```



```{r}
# Cardio plot function

medvisit_summary_function <- function(data, var, title_label, y_label) {
  
  medvisit_summary <- data %>% 
    filter(winter_id == 1) %>% 
    #select(var) %>% 
    select(area, var) %>% 
    group_by(area) %>% 
    summarize_all(list(mean=mean, sd=sd, min=min, med=median, max=max), na.rm = TRUE)
  medvisit_summary <<- medvisit_summary
  
  medvisit_plot <- data %>% 
    filter(winter_id == 1) %>% 
    select(area, var) %>% 
    rename(plot_var = var) %>% 
    filter(!is.na(plot_var)) %>% 
    ggplot(aes(area, plot_var)) +
    geom_boxplot(aes(size = 1), lwd = 1.2, colour = "black", 
               fatten = 1, outlier.size = 1.5, width = 0.35) +
    stat_summary(fun.y=mean, geom="point", shape=17, size=4, color="red",
                 position=position_nudge(x = -0.1, y = 0)) +
    stat_summary(aes(label=round(..y.., digits = 1)), fun.y=mean, geom="text", 
                 size=7, position=position_nudge(x = -0.35, y = 0)) +
    stat_summary(fun.y=median, geom="point", shape=16, size=4, color="blue",
                 position=position_nudge(x = 0.1, y = 0)) +
    stat_summary(aes(label=round(..y.., digits = 1)), fun.y=median, geom="text", 
                 size=7, position=position_nudge(x = 0.35, y = 0)) +
    theme_minimal() +
    labs(title = title_label, subtitle = "Mean = Red, Median = Blue") +
    ylab(y_label) +
    theme(title = element_text(size = 20, colour = "black"),
          axis.text.x = element_text(size = 16, colour = "black"),
          axis.text.y = element_text(size = 16, colour = "black"),
          axis.title.y = element_text(size = 16, colour = "black"),
          axis.title.x = element_blank(),
          axis.line.x = element_line(colour = "black", size = 1.2), 
          axis.line.y = element_line(colour = "black", size = 1.2), 
          axis.ticks = element_blank()) 
  medvisit_plot
  
}

medvisit_summary_function(elders_medvisit, "sp02", "Sp02", "%")
medvisit_summary_function(elders_medvisit, "pr", "Sp02 pulse rate", "beats/min")
medvisit_summary_function(elders_medvisit, "bp_sys", "Systolic blood pressure", "mmHg")
medvisit_summary_function(elders_medvisit, "bp_dia", "Diastolic blood pressure", "mmHg")
medvisit_summary_function(elders_medvisit, "hr", "Heart rate from BP", "beats/min")
medvisit_summary_function(elders_medvisit, "age", "Age", "years")
medvisit_summary_function(elders_medvisit, "height_inches", "Height", "inches")
medvisit_summary_function(elders_medvisit, "weight_lbs", "Weight", "pounds")
medvisit_summary_function(elders_medvisit, "bmi", "BMI", "kg/m2")
```


# Spirometry outcomes from Med visit
## Using only observations when spiro session graded as "acceptable"
```{r}
medvisit_plot <- elders_medvisit %>% 
  filter(winter_id == 1) %>% 
  filter(spiro_status == "Acceptable") %>% 
  select(area, fvc, fev1, fev1_fvc_ratio, fvc_pp, fev1_pp) %>% 
  pivot_longer(cols = c("fvc":"fev1_pp"), names_to = "var") %>% 
  filter(!is.na(value)) %>% 
  ggplot(aes(area, value)) +
    geom_boxplot(aes(size = 1), lwd = 1.2, colour = "black", 
               fatten = 1, outlier.size = 1.5, width = 0.35) +theme_minimal() +
    theme(strip.text = element_text(size = 16, colour = "black"),
          axis.text.x = element_text(size = 16, colour = "black"),
          axis.text.y = element_text(size = 16, colour = "black"),
          axis.title.y = element_text(size = 16, colour = "black"),
          axis.title.x = element_blank(),
          axis.line.x = element_line(colour = "black", size = 1.2), 
          axis.line.y = element_line(colour = "black", size = 1.2), 
          axis.ticks = element_blank()) +
    facet_wrap(~var, scales = "free_y")
medvisit_plot
```


```{r}
# Spiro plot function

medvisit_summary_function <- function(data, var, title_label, y_label) {
  
  medvisit_summary <- data %>% 
    filter(winter_id == 1) %>% 
    filter(spiro_status == "Acceptable") %>% 
    #select(var) %>% 
    select(area, var) %>% 
    group_by(area) %>% 
    summarize_all(list(mean=mean, sd=sd, min=min, med=median, max=max), na.rm = TRUE)
  medvisit_summary <<- medvisit_summary
  
  medvisit_plot <- data %>% 
    filter(winter_id == 1) %>% 
    filter(spiro_status == "Acceptable") %>% 
    select(area, var) %>% 
    rename(plot_var = var) %>% 
    na.exclude() %>% 
    ggplot(aes(area, plot_var)) +
    geom_boxplot(aes(size = 1), lwd = 1.2, colour = "black", 
               fatten = 1, outlier.size = 1.5, width = 0.35) +
    stat_summary(fun.y=mean, geom="point", shape=17, size=4, color="red",
                 position=position_nudge(x = -0.1, y = 0)) +
    stat_summary(aes(label=round(..y.., digits = 1)), fun.y=mean, geom="text", 
                 size=7, position=position_nudge(x = -0.3, y = 0)) +
    stat_summary(fun.y=median, geom="point", shape=16, size=4, color="blue",
                 position=position_nudge(x = 0.1, y = 0)) +
    stat_summary(aes(label=round(..y.., digits = 1)), fun.y=median, geom="text", 
                 size=7, position=position_nudge(x = 0.3, y = 0)) +
    theme_minimal() +
    labs(title = title_label, subtitle = "Mean = Red, Median = Blue") +
    ylab(y_label) +
    theme(title = element_text(size = 20, colour = "black"),
          axis.text.x = element_text(size = 16, colour = "black"),
          axis.text.y = element_text(size = 16, colour = "black"),
          axis.title.y = element_text(size = 16, colour = "black"),
          axis.title.x = element_blank(),
          axis.line.x = element_line(colour = "black", size = 1.2), 
          axis.line.y = element_line(colour = "black", size = 1.2), 
          axis.ticks = element_blank()) 
  medvisit_plot
  
}

medvisit_summary_function(elders_medvisit, "fvc", "Forced vital capacity", "liters")
medvisit_summary_function(elders_medvisit, "fev1", "Forced expiratory volume", "liters")
medvisit_summary_function(elders_medvisit, "fev1_fvc_ratio", "FEV1/FVC ratio", " ")
medvisit_summary_function(elders_medvisit, "fvc_pp", "FVC percent predicted", "%")
medvisit_summary_function(elders_medvisit, "fev1_pp", "FEV1 percent predicted", "%")
```


```{r, fig.height=3, fig.width=2.75}
# function for poster plots

medvisit_summary_function <- function(data, var, title_label, y_label) {
  
  medvisit_plot <- data %>% 
    filter(winter_id == 1) %>% 
    filter(spiro_status == "Acceptable") %>% 
    select(area, var) %>% 
    rename(plot_var = var) %>% 
    na.exclude() %>% 
    ggplot(aes(area, plot_var)) +
    geom_boxplot(aes(size = 1), lwd = 1.2, colour = "black", fill = "#56B4E9",
               fatten = 1, outlier.size = 1.5, width = 0.35) +
    stat_summary(fun.y=mean, geom="point", shape=17, size=4, color="red") +
    theme_minimal() +
    labs(title = title_label) +
    ylab(y_label) +
    theme(title = element_text(size = 16, colour = "black"),
          axis.text.x = element_text(size = 16, colour = "black"),
          axis.text.y = element_text(size = 16, colour = "black"),
          axis.title.y = element_text(size = 16, colour = "black"),
          axis.title.x = element_blank(),
          axis.line.x = element_line(colour = "black", size = 1.2), 
          axis.line.y = element_line(colour = "black", size = 1.2), 
          axis.ticks = element_blank()) 
  medvisit_plot
  
}

medvisit_summary_function(elders_medvisit, "fvc", "Forced vital \ncapacity", "Liters")
medvisit_summary_function(elders_medvisit, "fev1", "Forced expiratory \nvolume", "Liters")
medvisit_summary_function(elders_medvisit, "fev1_fvc_ratio", "FEV1/FVC \nratio", " ")
medvisit_summary_function(elders_medvisit, "fvc_pp", "FVC percent \npredicted", "%")
medvisit_summary_function(elders_medvisit, "fev1_pp", "FEV1 percent \npredicted", "%")
medvisit_summary_function(elders_medvisit, "bp_sys", "Systolic blood \npressure", "mmHg")
medvisit_summary_function(elders_medvisit, "bp_dia", "Diastolic blood \npressure", "mmHg")
medvisit_summary_function(elders_medvisit, "age", "Age", "Years")
medvisit_summary_function(elders_medvisit, "bmi", "Body mass \nindex", "kg/m2")
```


```{r, fig.height=3, fig.width=3}
# poster figures
obstruction_data <- elders_medvisit %>% 
  arrange(home, adult_id_num, winter_id, sampling_visit) %>% 
  mutate(hypertension = if_else(bp_sys >= 140 | bp_dia >= 90, "Yes", "No"),
         obstruction = if_else(fev1_fvc_ratio < 0.7, "Yes", "No")) %>% 
  select(area, home, home_winter_id, winter_id, sampling_visit, adult_id_num,
         hypertension, obstruction, spiro_status, bp_sys, bp_dia) %>%
  filter(winter_id == 1) %>% 
  filter(spiro_status == "Acceptable") %>% 
  group_by(area, adult_id_num) %>% 
  mutate(obs_any = if_else(obstruction == "Yes" | lead(obstruction) == "Yes", "Yes", "No"),
         obs_any = if_else(is.na(obs_any), obstruction, obs_any)) %>% 
  ungroup() %>% 
  distinct(area, adult_id_num, .keep_all = TRUE) %>% 
  count(obs_any)
obstruction_data


hypertension_data <- elders_medvisit %>% 
  arrange(home, adult_id_num, winter_id, sampling_visit) %>% 
  mutate(hypertension = if_else(bp_sys >= 140 | bp_dia >= 90, "Yes", "No"),
         obstruction = if_else(fev1_fvc_ratio < 0.7, "Yes", "No")) %>% 
  select(area, home, home_winter_id, winter_id, sampling_visit, adult_id_num,
         hypertension, obstruction, spiro_status, bp_sys, bp_dia) %>%
  filter(winter_id == 1) %>% 
  group_by(area, adult_id_num) %>% 
  mutate(hyp_any = if_else(hypertension == "Yes" | lead(hypertension) == "Yes", "Yes", "No"),
         hyp_any = if_else(is.na(hyp_any), hypertension, hyp_any)) %>% 
  ungroup() %>% 
  distinct(area, adult_id_num, .keep_all = TRUE) %>% 
  count(hyp_any)
hypertension_data

medvisit_summary_function <- function(data, var, title_label) {
  
  medvisit_plot <- data %>% 
    select(area, var) %>% 
    rename(plot_var = var) %>% 
    filter(!is.na(plot_var)) %>%  
    ggplot() +
    geom_bar(aes(fct_rev(area), fill = plot_var)) +
    theme_minimal() +
    coord_flip() +
    theme(axis.text.x = element_text(size = 16, colour = "black", 
                                     vjust = 0.7, hjust = 0.7),
          axis.text.y = element_text(size = 16, colour = "black"),
          title = element_text(size = 16, colour = "black"),
          legend.text = element_text(size = 16, colour = "black"),
          legend.title = element_blank(),
          legend.position = "top",
          axis.title.y = element_blank(),
          axis.title.x = element_blank(),
          axis.line.x = element_line(colour = "black", size = 1.2), 
          axis.line.y = element_line(colour = "black", size = 1.2), 
          axis.ticks = element_blank(),
          panel.grid = element_blank()) +
    labs(title = title_label) +
    scale_fill_manual(values = cbPalette)
  medvisit_plot
  
}

medvisit_summary_function(hypertension_data, "hyp_any", "Stage 2 \nhypertension")
medvisit_summary_function(obstruction_data, "obs_any", "FEV1/FVC ratio \n< 0.7")
```


```{r}
summary_stats <- elders_medvisit %>% 
  filter(winter_id == 1) %>% 
  #filter(spiro_status == "Acceptable") %>% 
  #filter(!is.na(bp_sys)) %>% 
  #group_by(area) %>% 
  distinct(area, adult_id_num) %>% # use home and adult_id_num
  summarize(n())
summary_stats

summary_stats <- elders_medvisit %>% 
  filter(winter_id == 1) %>% 
  distinct(area, adult_id_num, .keep_all = TRUE) %>% 
  #group_by(area) %>% 
  count(gender)
summary_stats

summary_stats <- elders_medvisit %>% 
  filter(winter_id == 1) %>% 
  distinct(area, adult_id_num, .keep_all = TRUE) %>% 
  #group_by(area) %>% 
  summarize(mean(bmi, na.rm = TRUE), sd(bmi, na.rm = TRUE), 
            min(bmi, na.rm = TRUE), median(bmi, na.rm = TRUE), 
            max(bmi, na.rm = TRUE))
summary_stats
```
