---
title: 'EldersAIR: data merging for analysis dataset'
author: "Ethan Walker"
date: "Started 11 March 2021, Updated 7 May 2021"
output:
  powerpoint_presentation: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, eval = TRUE, 
                      include = TRUE, warning = FALSE,
                      fig.height = 6, fig.width = 8)
```

```{r, message=FALSE}
library(tidyverse)
library(readxl)
library(naniar)
library(lubridate)
library(zoo)
library(knitr)
jv_palette <- c("#330099","#CC0066","#FF6633", 
                 "#0099CC", "#FF9900","#CC6633",
                  "#FF3366", "#33CC99", "#33999")
cbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", 
               "#0072B2", "#D55E00", "#CC79A7")
```


```{r}
# Load individual datasets

file_path <- c("C:/Users/ethan.walker/Box/Ethan Walker UM/R/EldersAIR/")

elders_ids_linked <- read_rds(paste0(file_path, "Output/elders_ids_linked.rds")) 

elders_demographics <- read_rds(paste0(file_path, "Output/elders_demographics.rds"))

elders_medvisit_clean <- read_rds(paste0(file_path, "Output/elders_medvisit_clean.rds"))

#elders_at_home_log_clean <- read_rds(paste0(file_path, "Output/elders_at_home_log_clean.rds"))

elders_health_hx_clean <- read_rds(paste0(file_path, "Output/elders_health_hx_clean.rds"))

elders_health_extra_clean <- read_rds(paste0(file_path, "Output/elders_health_extra_clean.rds"))

#elders_pm_long <- read_rds(paste0(file_path, "Output/elders_pm_clean.rds")) 

elders_pm_at_home_visit <- read_rds(paste0(file_path, "Output/pm_at_home_visit.rds")) 

npt_micropem_clean <- read_rds(paste0(file_path, "Output/npt_micropem_clean.rds")) 

elders_stove_grades_clean <- read_rds(paste0(file_path, "Output/elders_stove_grades_clean.rds")) 

elders_stove_usage_clean <- read_rds(paste0(file_path, "Output/elders_stove_usage_clean.rds")) 

elders_kw_report_clean <- read_rds(paste0(file_path, "Output/elders_kw_report_clean.rds")) 

elders_filter_type <- read_rds(paste0(file_path, "Output/elders_filter_type.rds")) 

elders_temp_rh_clean <- read_rds(paste0(file_path, "Output/elders_temp_rh_clean.rds")) 

elders_home_char_clean <- read_rds(paste0(file_path, "Output/elders_home_char_clean.rds")) 

elders_home_activity_clean <- read_rds(paste0(file_path, "Output/elders_home_activity_clean.rds")) 

elders_moisture_clean <- read_rds(paste0(file_path, "Output/elders_moisture_clean.rds")) 

elders_fitbit_visit <- read_rds(paste0(file_path, "Output/elders_fitbit_visit.rds")) 
```


Prep demographics data for merging
```{r}
demographics <- elders_demographics %>% 
  arrange(area, adult_id_char, winter_id) %>% 
  group_by(area, adult_id_char, winter_id) %>% 
  rename("1" = sampling_date,
         "2" = sampling_date2) %>% 
  pivot_longer(cols = c("1", "2"), names_to = "sampling_visit",
               values_to = "sampling_date") %>% 
  mutate(sampling_visit = as.factor(sampling_visit)) %>% 
  select(area, home, home_id_num, home_winter_id, adult_id_char, adult_id_num,
         winter_id, sampling_visit, sampling_date, treatment, intervention_date,
         intervention_time, hispanic:residents_under18, -age) %>% 
  filter(!is.na(sampling_date)) %>% 
  arrange(area, adult_id_char, winter_id, sampling_visit)
```


Merge PM, health, stove data 
One observation per sampling visit (up to 4 obs per adult/home)
```{r}
health_pm_visit <- elders_medvisit_clean %>% 
  full_join(elders_pm_at_home_visit,
            by = c("area", "home", "home_id_num", "adult_id_char", "adult_id_num",
                   "home_winter_id", "winter_id", "treatment", "sampling_visit")) %>% 
  left_join(demographics,
            by = c("area", "home", "home_id_num", "adult_id_char", "adult_id_num",
                   "home_winter_id", "winter_id", "treatment", "sampling_visit")) %>% 
  left_join(elders_health_extra_clean,
            by = c("area", "home", "home_id_num", "adult_id_char", "adult_id_num",
                   "home_winter_id", "winter_id", "treatment", "sampling_visit")) %>% 
  left_join(elders_health_hx_clean,
            by = c("area", "home", "home_id_num", "adult_id_char", "adult_id_num",
                   "home_winter_id", "winter_id", "treatment")) %>% 
  left_join(npt_micropem_clean,
            by = c("area", "home_id_num", "adult_id_char", 
                   "home_winter_id", "winter_id", "sampling_visit")) %>% 
  left_join(elders_stove_grades_clean,
            by = c("area", "home", "home_id_num", "treatment")) %>% 
  left_join(elders_stove_usage_clean,
            by = c("area", "home", "home_id_num", 
                   "home_winter_id", "winter_id", "treatment", "sampling_visit")) %>% 
  left_join(elders_fitbit_visit,
            by = c("area", "home_winter_id", "adult_id_num", 
                   "winter_id", "sampling_visit")) %>% 
  left_join(elders_kw_report_clean,
            by = c("area", "home_winter_id")) %>% 
  left_join(elders_filter_type,
            by = c("area", "home_winter_id")) %>% 
  left_join(elders_temp_rh_clean,
            by = c("area", "home_winter_id", "sampling_visit")) %>% 
  left_join(elders_home_activity_clean,
            by = c("area", "home", "home_id_num", 
                   "home_winter_id", "winter_id", "treatment", "sampling_visit")) %>% 
  left_join(elders_home_char_clean,
            by = c("area", "home", "home_id_num", 
                   "home_winter_id", "winter_id", "treatment")) %>% 
  left_join(elders_moisture_clean,
            by = c("area", "home_winter_id", "sampling_visit")) 


elders_cleaned_dataset_by_visit <- health_pm_visit %>% 
  mutate(home_floors = as.factor(home_floors),
         home_floors_2level = fct_collapse(home_floors,
                                           "1" = "1",
                                           "2+" = c("2", "3")),
         home_sqm = home_sqft*0.0929,
         home_sqm_2level = cut(home_sqm, breaks = c(0, 112, 10000),
                               labels = c("<111", "111+")),
         home_bedrooms = as.numeric(home_bedrooms),
         home_year_built_2level = cut(home_year_built, 
                                      breaks = c(0, 1981, 10000),
                                      labels = c("<1981", "1981+")),
         home_pets = as.factor(home_pets),
         home_pets_3level = fct_collapse(home_pets,
                                         "0" = "0",
                                         "1" = "1",
                                         "2+" = c("2", "3", "4", "5", "6", "7", "10")),
         income = as.factor(income),
         income_3level = fct_collapse(income,
                                      "< $20,000" = "< $20,000",
                                      "$20,000 to $39,999" = c("$20,000 to $29,999", "$30,000 to $39,999"),
                                      "$40,000+" = c("$40,000 to $49,999", "$50,000 to $74,999", 
                                                     "$75,000 to $99,999", ">= $100,000")),
         stove_age = factor(stove_age,
                            levels = c("0-5 years old", "6-10 years old", "11-15 years old",
                                       "16 + years old", "Do not know")),
         chimney_clean = factor(chimney_clean,
                            levels = c("Less than 6 months ago", "6-12 months ago", 
                                       "12-18 months ago", "More than 18 months ago")),
         burn_level = factor(burn_level,
                            levels = c("No burning", "Light burning", 
                                       "Average burning", "Heavy burning")),
         wood_collect = factor(wood_collect,
                            levels = c("Less than 1 week", "Between 1 week and 1 month", 
                                       "Between 1 month and 3 months", "Between 3 months and 6 months",
                                       "Between 6 months and 1 year", "More than 1 year"))) %>% 
  mutate(treatment = factor(treatment,
                            levels = c("Placebo", "Filter", "Education"),
                            labels = c("Placebo", "Filter", "Education")),
         visit_intervention_diff = round(difftime(sampling_date, intervention_date, 
                                            units = "days"), digits = 0),
         visit_intervention_diff = as.numeric(visit_intervention_diff),
         visit_intervention_diff = if_else(winter_id == 1, 9999,
                                           visit_intervention_diff)) %>% 
  # All but 4 homes (all NPT homes that used Large Filtretes) in the Filter arm used Winix units
  # Filter type isn't really feasible to use in the analysis due to this small sample size
  mutate(treatment_filter_type = as.character(treatment),
         filter_type = as.character(filter_type),
         treatment_filter_type2 = if_else(treatment_filter_type == "Filter", filter_type,
                                         treatment_filter_type),
         treatment_filter_type = factor(treatment_filter_type2,
                                        levels = c("Placebo", "Education",
                                                   "Large Filtrete", "Winix")),
         filter_type = as.factor(filter_type),
         kw_perc_expected = if_else(treatment == "Education", 100, kw_perc_expected)) %>% 
  mutate(treatment = as.character(treatment),
         perc_exp_quart = cut(kw_perc_expected,
                                  breaks = c(0, 25, 46, 71, 1000),
                                  labels = c("0-25 compliance", "25-50 compliance",
                                             "50-75 compliance", "75-100 compliance")),
         perc_exp_quart = as.character(perc_exp_quart),
         filter_compliance = if_else(treatment == "Filter",
                                     perc_exp_quart, 
                                     treatment),
         treatment = factor(treatment,
                            levels = c("Placebo", "Education", "Filter")),
         filter_compliance = factor(filter_compliance,
                                    levels = c("Placebo", "Education",
                                               "0-25 compliance", "25-50 compliance",
                                               "50-75 compliance", "75-100 compliance"))) %>% 
  select(-treatment_filter_type2) %>% 
  mutate(income_2level = fct_collapse(income,
                                      "20,000 +" = c("$20,000 to $29,999", "$30,000 to $39,999",
                                                     "$40,000 to $49,999", "$50,000 to $74,999",
                                                     "$75,000 to $99,999", ">= $100,000")),
         burn_level_3level = fct_collapse(burn_level,
                                          "No/light burning" = c("No burning", "Light burning")),
         stove_age_2level = fct_collapse(stove_age,
                                         "0-10 years old" = c("0-5 years old", "6-10 years old"),
                                         "11+ years old" = c("11-15 years old", "16 + years old")),
         chimney_clean_3level = fct_collapse(chimney_clean,
                                             "12+ months ago" =
                                               c("12-18 months ago", "More than 18 months ago")),
         wood_collect_3level = fct_collapse(wood_collect,
                                            "< 1 month" = c("Less than 1 week", "Between 1 week and 1 month"),
                                            "1 to 6 months" = c("Between 1 month and 3 months", "Between 3 months and 6 months"),
                                            "6+ months" = c("Between 6 months and 1 year", "More than 1 year")),
         age_2level = cut(age, breaks = c(50, 68, 100),
                          labels = c("50 to 68", "69+")),
         bmi_2level = cut(bmi, breaks = c(0, 29, 100),
                          labels = c("<30", "30+")),
         hypertension = if_else(bp_sys >= 140 | bp_dia >= 90, "Yes", "No"),
         steps_4level = cut(steps, breaks = c(0, 1312, 3814, 6734, 31951),
                            labels = c("Q1", "Q2", "Q3", "Q4")),
         steps_2level = cut(steps, breaks = c(0, 3814, 32000),
                            labels = c("<3815", "3815+"))) %>% 
  group_by(adult_id_char, winter_id) %>% 
  mutate(sum_act_smoking = sum(home_act_smoking, na.rm = T),
         sum_act_candle = sum(home_act_candle, na.rm = T),
         sum_act_door = sum(home_act_door, na.rm = T),
         sum_act_gas = sum(home_act_gas, na.rm = T),
         sum_act_elect = sum(home_act_elect, na.rm = T),
         sum_act_propane = sum(home_act_propane, na.rm = T),
         sum_act_oil = sum(home_act_oil, na.rm = T),
         sum_act_incense = sum(home_act_incense, na.rm = T),
         sum_act_kerosene = sum(home_act_kerosene, na.rm = T),
         sum_act_windows = sum(home_act_windows, na.rm = T),
         sum_act_sweep = sum(home_act_sweep, na.rm = T)) %>% 
  group_by(adult_id_char) %>% 
  arrange(adult_id_char, sampling_date) %>% 
  mutate(first_date = first(sampling_date),
         cohort = round_date(first_date, unit = "year")) %>% 
  separate(cohort, c("cohort", "trash"), sep = "-") %>% 
  mutate(cohort = as.factor(cohort)) %>% 
  select(-trash) %>% 
  ungroup()
  


elders_distinct <- elders_cleaned_dataset_by_visit %>% 
  arrange(area, home, winter_id, sampling_visit) %>% 
  distinct(home, .keep_all = T)

median(elders_distinct$home_year_built, na.rm = T)
table(elders_distinct$sum_act_candle)
```

Save final dataset
```{r}
write_rds(elders_cleaned_dataset_by_visit, paste0(file_path, "Output/elders_cleaned_dataset_by_visit.rds"))

write_csv(elders_cleaned_dataset_by_visit, paste0(file_path, "Output/elders_cleaned_dataset_by_visit.csv"), na = " ")

# save variable names to use in data dictionary
save_var_names <- data.frame(t(elders_cleaned_dataset_by_visit)) %>% 
  rownames_to_column() %>% 
  select(rowname)

write_csv(save_var_names, paste0(file_path, "Output/health_pm_visit_var_names.csv"))
```


Merge PM and at-home data and summarize by sampling visit
## This step is done and data is loaded above
```{r}
elders_at_home_log <- elders_at_home_log_clean %>% 
  select(-home_winter_id, -home, -treatment)

pm_at_home_ranked <- elders_pm_long %>% 
  separate(pm_datetime_new, c("pm_date", "pm_time"), sep = " ", remove = F) %>% 
  group_by(area, home, winter_id, sampling_visit) %>% 
  distinct(pm_date, .keep_all = T) %>% 
  mutate(at_home_day = rank(pm_date)) %>% 
  select(area, home, winter_id, sampling_visit, pm_date, at_home_day) %>% 
  ungroup()

pm_at_home_visit <- elders_pm_long %>% 
  mutate(sample_datetime = round_date(pm_datetime_new, unit = "hour")) %>% 
  separate(sample_datetime, c("pm_date", "sample_time"), sep = " ", remove = F) %>% 
  left_join(pm_at_home_ranked, by = c("area", "home", "winter_id", 
                                      "sampling_visit", "pm_date")) %>% 
  group_by(area, home, winter_id, sampling_visit, at_home_day) %>% 
  mutate(pm_mean_at_home_day = mean(pm, na.rm = T)) %>% 
  group_by(area, home, winter_id, sampling_visit, at_home_day, sample_time) %>% 
  mutate(pm_mean_at_home_hour = mean(pm, na.rm = T),
         at_home_day = as.factor(at_home_day)) %>% 
  ungroup() %>% 
  distinct(area, home, winter_id, sampling_visit, at_home_day, sample_time, .keep_all = T) %>% 
  full_join(elders_at_home_log, by = c("area", "home_id_num", "winter_id", 
                                       "sampling_visit", "at_home_day", "sample_time")) %>% 
  filter(at_home == "Yes") %>% 
  group_by(area, adult_id_num, winter_id, sampling_visit) %>% 
  mutate(pm_mean_at_home_visit = mean(pm, na.rm = T)) %>% 
  group_by(area, adult_id_num, winter_id) %>% 
  mutate(pm_mean_at_home_winter = mean(pm, na.rm = T)) %>% 
  ungroup() %>% 
  distinct(area, adult_id_num, winter_id, sampling_visit, .keep_all = T) %>% 
  select(area, adult_id_num, adult_id_char, home_id_num, home, home_winter_id,
         winter_id, sampling_visit, treatment,
         pm_sample_interval, pm_mean_winter, pm_mean_visit, pm_mean_at_home_visit,
         pm_mean_at_home_winter, dtid, sample_obs, pm_comments) %>% 
  filter(!is.na(home)) %>% 
  mutate(area = as.factor(area)) %>% 
  mutate_at(vars(home_id_num:winter_id), as.factor) %>% 
  ungroup() %>% 
  arrange(area, adult_id_num, winter_id, sampling_visit)

#summary(pm_at_home_visit)

write_rds(pm_at_home_visit, paste0(file_path, "Output/pm_at_home_visit.rds"))
```

