---
title: "Elders Moisture Summary"
author: "Ethan Walker"
date: "Started 5 March 2020, Updated 12 March 2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, eval = TRUE, 
                      include = TRUE, warning = FALSE)
```

```{r, message=FALSE}
library(tidyverse)
library(lubridate)
library(readr)
library(knitr)
```

```{r}
file_path <- c("C:/Users/ethan.walker/Box/Ethan Walker UM/R/EldersAIR/")

# Load data
moisture_clean <- read_rds(paste0(file_path, "Output/elders_moisture_clean.rds"))
elders_ids_linked <- read_rds(paste0(file_path, "Output/elders_ids_linked.rds"))
elders_pm <- read_rds(paste0(file_path, "Output/elders_pm_clean.rds"))
```


```{r}
# Moisture content summary stats
## Average of 3 measurements

moisture_n <- moisture_clean %>% 
  filter(winter_id == 1) %>% 
  group_by(area) %>%
  filter(!is.na(moisture_ave)) %>% 
  distinct(home) %>% 
  summarize(n())
```

# Moisture content by area
```{r}
summary_moisture <- moisture_clean %>%
  filter(winter_id == 1) %>% 
  group_by(area) %>% 
  summarize(mean = mean(moisture_ave, na.rm = TRUE), 
            SD = sd(moisture_ave, na.rm = TRUE),
            median = median(moisture_ave, na.rm = TRUE),
            min = min(moisture_ave, na.rm = TRUE), 
            max = max(moisture_ave, na.rm = TRUE)) %>%
  select(-area) %>% 
  t() 
kable(summary_moisture, col.names = c("Navajo", "Nez Perce"), 
      digits = 1, align = "c")
```

# Moisture content total
```{r}
summary_moisture <- moisture_clean %>%
  filter(winter_id == 1) %>% 
  summarize(mean = mean(moisture_ave, na.rm = TRUE), 
            SD = sd(moisture_ave, na.rm = TRUE),
            median = median(moisture_ave, na.rm = TRUE),
            min = min(moisture_ave, na.rm = TRUE), 
            max = max(moisture_ave, na.rm = TRUE)) %>%
  t() 
kable(summary_moisture, digits = 1, align = "c")
```

# Was wood split?
```{r}
wood_split <- moisture_clean %>% 
  filter(winter_id == 1) %>% 
  filter(!is.na(moisture_split)) %>% 
  group_by(area, moisture_split) %>% 
  summarise(n = n())
kable(wood_split, align = "c")
```

```{r, fig.height=6, fig.width=5}
boxplots_moisture <- moisture_clean %>% 
  filter(winter_id == 1) %>% 
  select(area, moisture_ave) %>% 
  na.exclude() %>% 
  ggplot(aes(area, moisture_ave)) +
    geom_boxplot(aes(size = 1), lwd = 1.2, colour = "black", 
               fatten = 1, outlier.size = 1.5, width = 0.35) +
    stat_summary(fun.y=mean, geom="point", shape=17, size=4, color="red",
                 position=position_nudge(x = -0.1, y = 0)) +
    stat_summary(aes(label=round(..y.., digits = 1)), fun.y=mean, geom="text", 
                 size=7, position=position_nudge(x = -0.35, y = 0)) +
    stat_summary(fun.y=median, geom="point", shape=16, size=4, color="blue",
                 position=position_nudge(x = 0.1, y = 0)) +
    stat_summary(aes(label=round(..y.., digits = 1)), fun.y=median, geom="text", 
                 size=7, position=position_nudge(x = 0.35, y = 0)) +
    theme_minimal() +
    ylim(0, 50) +
    #geom_hline(yintercept = 50, color = "red", size = 1.2) +
    labs(title = "Mean wood moisture content" , y = "%") +
    #labs(aes(x = "", y = paste("48-hour indoor PM "[2.5], " (", mu, g/m^3, ")"))) +
    theme(axis.text.x = element_text(size = 16, colour = "black"),
          axis.text.y = element_text(size = 16, colour = "black"),
          axis.title.y = element_text(size = 16,
                                      margin = margin(t = 0, r = 20, b = 0, l = 0)),
          title = element_text(size = 18, colour = "black"),
          axis.title.x = element_blank(),
          axis.line.x = element_line(colour = "black", size = 1.2), 
          axis.line.y = element_line(colour = "black", size = 1.2), 
          axis.ticks = element_blank())
boxplots_moisture
```



```{r}
#### Abstract/manuscript tables ####

# Filter for homes that have PM data



pm_homes <- elders_pm %>% 
  filter(winter_id == 1) %>% 
  group_by(area, home, sampling_visit) %>% 
  mutate(initial_obs = if_else(pm_datetime_new == first_datetime, 1, 0)) %>% 
  filter(initial_obs == 1) %>% 
  mutate(pm_home = "true") %>% 
  select(area, home, home_winter_id, sampling_visit, pm_home, first_datetime) %>% 
  separate(first_datetime, c("first_date", "first_time"), sep = " ", remove = TRUE) %>% 
  ungroup() %>% 
  arrange(area, home)

moisture_filtered <- moisture_clean %>% 
  # change to correct joining data of interest
  left_join(pm_homes, by = c("area", "home", "home_winter_id")) %>% 
  filter(pm_home == "true") %>% 
  filter(winter_id == 1) %>% 
  ungroup() %>%
  arrange(area, home)

moisture_filtered_time <- moisture_filtered %>% 
  mutate(moisture_date = ymd(moisture_date),
         first_date = ymd(first_date),
         time_diff = moisture_date - first_date,
         time_diff = as.numeric(abs(time_diff))) %>% 
  group_by(home, sampling_visit) %>% 
  mutate(time_diff_rank = if_else(time_diff == min(time_diff, na.rm = TRUE), 1, 0)) %>%
  ungroup() %>% 
  filter(time_diff_rank == 1)
```


```{r, include=FALSE}
# Summarize numeric vars
elders_moisture <- moisture_filtered_time %>%  
  group_by(area) %>% 
  summarize("Mean" = mean(moisture_ave, na.rm = TRUE), 
            "SD" = sd(moisture_ave, na.rm = TRUE),
            "min" = min(moisture_ave, na.rm = TRUE), 
            "med" = median(moisture_ave, na.rm = TRUE), 
            "max" = max(moisture_ave, na.rm = TRUE))
kable(elders_moisture, digits = 1, align = "c")

# Summarize numeric vars
elders_moisture <- moisture_filtered_time %>%  
  #group_by(area) %>% 
  summarize("Mean" = mean(time_diff, na.rm = TRUE), 
            "SD" = sd(time_diff, na.rm = TRUE),
            "min" = min(time_diff, na.rm = TRUE), 
            "med" = median(time_diff, na.rm = TRUE), 
            "max" = max(time_diff, na.rm = TRUE))
kable(elders_moisture, digits = 1, align = "c")
```

